import type { Contact } from '../types';

// ─── Contacts (Leads) ─────────────────────────────────────────────────────────

export const MOCK_LEADS: Contact[] = [
  {
    id: 'lead_1',
    tenantId: 'tenant_demo',
    firstName: 'John',
    lastName: 'Cruz',
    customerType: 'Organization',
    companyName: 'ABC Manufacturing Corp.',
    contactPerson: 'John Cruz',
    jobTitle: 'Senior IT Infrastructure Manager',
    email: 'j.cruz@abcmfg.ph',
    phone: '+63 2 8812 3456',
    serviceRequired: 'CCTV Surveillance System',
    leadSource: 'Referral',
    estimatedValue: 185000,
    assignedUserId: 'user_sales_1',
    expectedCloseDate: '2026-05-15',
    notes: 'Looking to install 50 IP cameras across their new manufacturing plant in Laguna. High priority.',
    status: 'Hot',
    updateStatus: 'Proposal sent for HQ CCTV system (₱185,000)',
    score: 95,
    createdAt: '2023-03-10T10:00:00.000Z',
    organizationId: 'org_1',
    productInterest: 'CCTV Surveillance System',
    streetAddress: 'Light Industry & Science Park II',
    city: 'Cabuyao',
    province: 'Laguna',
  },
  {
    id: 'lead_2',
    tenantId: 'tenant_demo',
    firstName: 'Maria',
    lastName: 'Santos',
    customerType: 'Organization',
    companyName: 'MetroTech Solutions Inc.',
    contactPerson: 'Maria Santos',
    jobTitle: 'VP of Technology',
    email: 'm.santos@metrotech.com.ph',
    phone: '+63 2 8705 9800',
    serviceRequired: 'Structured Cabling',
    leadSource: 'LinkedIn',
    estimatedValue: 45000,
    assignedUserId: 'user_sales_2',
    expectedCloseDate: '2026-06-01',
    notes: 'Needs complete Cat6A cabling for BPO floor prior to Q3 move-in.',
    status: 'Warm',
    updateStatus: 'Workload dependency survey initiated for cloud migration (₱520,000)',
    score: 75,
    createdAt: '2024-03-15T14:30:00.000Z',
    organizationId: 'org_2',
    productInterest: 'Structured Cabling',
    streetAddress: 'East Tower, PSE Center, Exchange Road',
    city: 'Pasig City',
    province: 'Metro Manila',
  },
  {
    id: 'lead_3',
    tenantId: 'tenant_demo',
    firstName: 'Michael',
    lastName: 'Reyes',
    customerType: 'Organization',
    companyName: 'Pacific Logistics & Supply Inc.',
    contactPerson: 'Michael Reyes',
    jobTitle: 'Director of Operations',
    email: 'm.reyes@pacificlogistics.ph',
    phone: '+63 2 8856 1200',
    serviceRequired: 'Biometrics & Door Access',
    leadSource: 'Website',
    estimatedValue: 750000,
    assignedUserId: 'user_sales_3',
    expectedCloseDate: '2026-04-20',
    notes: 'Requires enterprise Wi-Fi 6E & 10G fiber backbone for 4 logistics warehouses.',
    status: 'Hot',
    updateStatus: 'RF Heatmap survey completed for Wi-Fi 6E deployment (₱750,000)',
    score: 92,
    createdAt: '2023-09-20T09:15:00.000Z',
    organizationId: 'org_3',
    productInterest: 'Biometrics & Door Access',
    streetAddress: 'Manila International Cargo Terminal Area',
    city: 'Manila',
    province: 'Metro Manila',
  },
  {
    id: 'lead_4',
    tenantId: 'tenant_demo',
    firstName: 'Juan',
    lastName: 'Dela Cruz',
    customerType: 'Organization',
    companyName: 'Horizon Construction & Energy',
    contactPerson: 'Juan Dela Cruz',
    jobTitle: 'Procurement Head',
    email: 'j.delacruz@horizonenergy.ph',
    phone: '+63 2 8631 4455',
    serviceRequired: 'Fire Detection and Alarm System',
    leadSource: 'Cold Call',
    estimatedValue: 15000,
    assignedUserId: 'user_sales_1',
    expectedCloseDate: '2026-07-10',
    notes: 'Gathering FDAS budget quotes for FY2027 high-rise commercial project.',
    status: 'Cold',
    updateStatus: 'FDAS compliance upgrade deferred to FY2027 budget cycle',
    score: 35,
    createdAt: '2025-02-25T11:00:00.000Z',
    organizationId: 'org_4',
    productInterest: 'Fire Detection and Alarm System',
    streetAddress: 'Horizon Corporate Center, Julia Vargas Ave',
    city: 'Mandaluyong City',
    province: 'Metro Manila',
  },
  {
    id: 'lead_5',
    tenantId: 'tenant_demo',
    firstName: 'Patricia',
    lastName: 'Tan',
    customerType: 'Organization',
    companyName: 'Horizon Infrastructure Corp.',
    contactPerson: 'Patricia Tan',
    jobTitle: 'Head of Facilities & IT',
    email: 'p.tan@horizoninfra.ph',
    phone: '+63 2 8890 3322',
    serviceRequired: 'Servers & Data Cabinets',
    leadSource: 'Conference',
    estimatedValue: 250000,
    assignedUserId: 'user_sales_2',
    expectedCloseDate: '2026-05-30',
    notes: 'High potential data center upgrade for core server racks.',
    status: 'Warm',
    updateStatus: 'Annual SLA contract executed for 24/7 Managed IT (₱240,000)',
    score: 68,
    createdAt: '2024-03-05T16:45:00.000Z',
    organizationId: 'org_5',
    productInterest: 'Servers & Data Cabinets',
    streetAddress: 'Subic Bay Freeport Zone',
    city: 'Olongapo',
    province: 'Zambales',
  },
  {
    id: 'lead_6',
    tenantId: 'tenant_demo',
    firstName: 'Robert',
    lastName: 'Taylor',
    customerType: 'Organization',
    companyName: 'Nexus Digital Phils Inc.',
    contactPerson: 'Robert Taylor',
    jobTitle: 'Country Director',
    email: 'rtaylor@nexusdigital.ph',
    phone: '+63 2 8771 5000',
    serviceRequired: 'IP PBX & IP Phones',
    leadSource: 'Referral',
    estimatedValue: 98000,
    assignedUserId: 'user_sales_3',
    expectedCloseDate: '2026-04-15',
    notes: 'Biometrics access turnstiles contract signed and ready for installation.',
    status: 'Closed',
    updateStatus: 'Biometric turnstile door audit completed (₱98,000)',
    score: 100,
    createdAt: '2025-01-10T10:20:00.000Z',
    organizationId: 'org_6',
    productInterest: 'IP PBX & IP Phones',
    streetAddress: 'Cyberpark Tower 1, Araneta City',
    city: 'Quezon City',
    province: 'Metro Manila',
  },
  {
    id: 'lead_7',
    tenantId: 'tenant_demo',
    firstName: 'Robert',
    lastName: 'Mendoza',
    customerType: 'Individual',
    companyName: '',
    contactPerson: 'Robert Mendoza',
    jobTitle: 'Private Estate Owner',
    email: 'r.mendoza@private-estate.ph',
    phone: '+63 917 555 1234',
    serviceRequired: 'Electric Fence & Perimeter Security',
    leadSource: 'Email Campaign',
    estimatedValue: 30000,
    assignedUserId: 'user_sales_1',
    expectedCloseDate: '2026-08-01',
    notes: 'Residential contact. Wants top-tier physical security for private residence.',
    status: 'Cancelled',
    updateStatus: 'SIP trunk audit initiated for IP PBX & 80 SIP phones',
    score: 0,
    createdAt: '2025-02-01T13:10:00.000Z',
    streetAddress: 'Ayala Alabang Village',
    productInterest: 'Electric Fence & Perimeter Security',
    city: 'Muntinlupa',
    province: 'Metro Manila',
  },
  {
    id: 'lead_8',
    tenantId: 'tenant_demo',
    firstName: 'Angela',
    lastName: 'Dela Cruz',
    customerType: 'Organization',
    companyName: 'SecureNet Technologies Inc.',
    contactPerson: 'Angela Dela Cruz',
    jobTitle: 'Chief Information Security Officer',
    email: 'a.delacruz@securenet.ph',
    phone: '+63 2 8844 7788',
    serviceRequired: 'CCTV Surveillance System',
    leadSource: 'Referral',
    estimatedValue: 340000,
    assignedUserId: 'user_sales_1',
    expectedCloseDate: '2026-06-20',
    notes: 'Thermal vision CCTV cameras for R&D server vault cleanroom.',
    status: 'Hot',
    updateStatus: 'Thermal CCTV lab inspection finished (₱340,000)',
    score: 98,
    createdAt: '2025-04-01T10:00:00.000Z',
    organizationId: 'org_8',
    productInterest: 'CCTV Surveillance System',
    streetAddress: 'Uptown Tower 3, BGC',
    city: 'Taguig',
    province: 'Metro Manila',
  },
  {
    id: 'lead_9',
    tenantId: 'tenant_demo',
    firstName: 'David',
    lastName: 'Lim',
    customerType: 'Organization',
    companyName: 'Prime Retail Group Phils',
    contactPerson: 'David Lim',
    jobTitle: 'AVP for Retail IT',
    email: 'd.lim@primeretail.ph',
    phone: '+63 2 8687 9900',
    serviceRequired: 'Structured Cabling',
    leadSource: 'Website',
    estimatedValue: 165000,
    assignedUserId: 'user_sales_2',
    expectedCloseDate: '2026-07-15',
    notes: '10G Fiber backbone for flagship retail mall store network.',
    status: 'Warm',
    updateStatus: '10G Fiber backbone BOQ submitted to executive board (₱165,000)',
    score: 72,
    createdAt: '2025-04-02T14:30:00.000Z',
    organizationId: 'org_9',
    productInterest: 'Structured Cabling',
    streetAddress: 'Mega Tower, EDSA corner Julia Vargas',
    city: 'Mandaluyong',
    province: 'Metro Manila',
  },
  {
    id: 'lead_10',
    tenantId: 'tenant_demo',
    firstName: 'Norman',
    lastName: 'Osborn',
    customerType: 'Organization',
    companyName: 'Oscorp Industries',
    contactPerson: 'Norman Osborn',
    jobTitle: 'Chairman',
    email: 'n.osborn@oscorp.com',
    phone: '(555) 010-0123',
    serviceRequired: 'IP PBX & IP Phones',
    leadSource: 'Cold Call',
    estimatedValue: 25000,
    assignedUserId: 'user_sales_3',
    expectedCloseDate: '2026-09-01',
    notes: 'Initial inquiry about upgrading their legacy phone system.',
    status: 'Cold',
    updateStatus: 'IP PBX SIP trunk audit in progress (₱115,000)',
    score: 28,
    createdAt: '2026-04-03T09:15:00.000Z',
    organizationId: 'org_10',
    productInterest: 'IP PBX & IP Phones',
    streetAddress: '1000 Amazon St',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_11',
    tenantId: 'tenant_demo',
    firstName: 'Lex',
    lastName: 'Luthor',
    customerType: 'Organization',
    companyName: 'LexCorp',
    contactPerson: 'Lex Luthor',
    jobTitle: 'CEO',
    email: 'lex@lexcorp.com',
    phone: '(555) 010-1234',
    serviceRequired: 'Biometrics & Door Access',
    leadSource: 'LinkedIn',
    estimatedValue: 180000,
    assignedUserId: 'user_sales_2',
    expectedCloseDate: '2026-05-30',
    notes: 'Requires state-of-the-art biometric security for their main tower.',
    status: 'Hot',
    updateStatus: 'Retinal & facial biometrics final proposal sent (₱640,000)',
    score: 94,
    createdAt: '2026-04-04T11:00:00.000Z',
    organizationId: 'org_11',
    productInterest: 'Biometrics & Door Access',
    streetAddress: '1100 Silicon Blvd',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_12',
    tenantId: 'tenant_demo',
    firstName: 'Cave',
    lastName: 'Johnson',
    customerType: 'Organization',
    companyName: 'Aperture Science',
    contactPerson: 'Cave Johnson',
    jobTitle: 'Founder',
    email: 'cave@aperture.com',
    phone: '(555) 010-2345',
    serviceRequired: 'Servers & Data Cabinets',
    leadSource: 'Conference',
    estimatedValue: 300000,
    assignedUserId: 'user_sales_1',
    expectedCloseDate: '2026-08-15',
    notes: 'Looking for robust server solutions for their testing facilities.',
    status: 'Warm',
    updateStatus: 'Server rack BOQ approved by procurement (₱300,000)',
    score: 65,
    createdAt: '2026-04-05T16:45:00.000Z',
    organizationId: 'org_12',
    productInterest: 'Servers & Data Cabinets',
    streetAddress: '1200 Enterprise Rd',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_13',
    tenantId: 'tenant_demo',
    firstName: 'Sarah',
    lastName: 'Connor',
    customerType: 'Individual',
    companyName: '',
    contactPerson: 'Sarah Connor',
    jobTitle: 'Private Resident',
    email: 'sconnor@cyber-survive.org',
    phone: '(555) 010-9944',
    serviceRequired: 'High-Definition CCTV Coverage',
    leadSource: 'Referral',
    estimatedValue: 18000,
    assignedUserId: 'user_sales_3',
    expectedCloseDate: '2026-05-02',
    notes: 'Extremely focused on zero blind-spots around her residence. Requires night-vision cams.',
    status: 'Hot',
    updateStatus: 'Night-vision 4K CCTV survey completed (₱210,000)',
    score: 95,
    createdAt: '2026-04-06T08:30:00.000Z',
    streetAddress: '404 Hidden Valley Road',
    productInterest: 'High-Definition CCTV Coverage',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_14',
    tenantId: 'tenant_demo',
    firstName: 'Bruce',
    lastName: 'Wayne',
    customerType: 'Individual',
    companyName: '',
    contactPerson: 'Bruce Wayne',
    jobTitle: 'Private Resident',
    email: 'bwayne@wayne-estate.com',
    phone: '(555) 010-9000',
    serviceRequired: 'Intrusion Detection System',
    leadSource: 'Referral',
    estimatedValue: 89000,
    assignedUserId: 'user_sales_2',
    expectedCloseDate: '2026-06-10',
    notes: 'Wants specialized subterranean motion detectors and thermal cameras installed around private property lines.',
    status: 'Hot',
    updateStatus: 'Subterranean motion radar proposal delivered (₱890,000)',
    score: 99,
    createdAt: '2026-04-07T14:00:00.000Z',
    streetAddress: '1007 Mountain Crest Blvd',
    productInterest: 'Intrusion Detection System',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_15',
    tenantId: 'tenant_demo',
    firstName: 'Peter',
    lastName: 'Parker',
    customerType: 'Individual',
    companyName: '',
    contactPerson: 'Peter Parker',
    jobTitle: 'Freelance Photographer',
    email: 'pparker@dailybugle.net',
    phone: '(555) 012-3498',
    serviceRequired: 'Basic Home Assessment',
    leadSource: 'Web Form',
    estimatedValue: 1200,
    assignedUserId: 'user_sales_3',
    expectedCloseDate: '2026-05-15',
    notes: 'Needs simple door access logs and smart lock for apartment.',
    status: 'Warm',
    updateStatus: 'Smart lock installation scheduled for Friday',
    score: 60,
    createdAt: '2026-04-08T10:00:00.000Z',
    streetAddress: '20 Ingram St, Queens',
    productInterest: 'Basic Home Assessment',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_16',
    tenantId: 'tenant_demo',
    firstName: 'Clark',
    lastName: 'Kent',
    customerType: 'Organization',
    companyName: 'Daily Planet',
    contactPerson: 'Clark Kent',
    jobTitle: 'Investigative Journalist',
    email: 'ckent@dailyplanet.com',
    phone: '(555) 013-4455',
    serviceRequired: 'High-speed Network Routing',
    leadSource: 'Referral',
    estimatedValue: 55000,
    assignedUserId: 'user_sales_1',
    expectedCloseDate: '2026-06-01',
    notes: 'Upgrading the printing press and editorial floor network.',
    status: 'Hot',
    updateStatus: 'High-speed routing BOQ delivered to press manager (₱165,000)',
    score: 85,
    createdAt: '2026-04-09T09:15:00.000Z',
    organizationId: 'org_16',
    productInterest: 'High-speed Network Routing',
    streetAddress: '1600 Business Ctr',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_17',
    tenantId: 'tenant_demo',
    firstName: 'Diana',
    lastName: 'Prince',
    customerType: 'Organization',
    companyName: 'Themyscira Antiquities',
    contactPerson: 'Diana Prince',
    jobTitle: 'Curator',
    email: 'dprince@antiquities.org',
    phone: '(555) 018-9999',
    serviceRequired: 'Museum Security System',
    leadSource: 'Social Media Advertisement',
    estimatedValue: 210000,
    assignedUserId: 'user_sales_2',
    expectedCloseDate: '2026-07-20',
    notes: 'Requires artifact-level vibration sensors, glass-break detectors, and round-the-clock monitoring integration.',
    status: 'Hot',
    updateStatus: 'Museum laser security proposal presented to curators (₱280,000)',
    score: 97,
    createdAt: '2026-04-10T11:45:00.000Z',
    organizationId: 'org_17',
    productInterest: 'Museum Security System',
    streetAddress: '1700 Industrial Ave',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_18',
    tenantId: 'tenant_demo',
    firstName: 'Barry',
    lastName: 'Allen',
    customerType: 'Organization',
    companyName: 'Central City PD',
    contactPerson: 'Barry Allen',
    jobTitle: 'CSI Forensics',
    email: 'ballen@ccpd.gov',
    phone: '(555) 019-8877',
    serviceRequired: 'Lab Data Cabinets',
    leadSource: 'Cold Call',
    estimatedValue: 40000,
    assignedUserId: 'user_sales_3',
    expectedCloseDate: '2026-05-30',
    notes: 'Expanding the forensic labs, needs isolated subnet and secured data cabinets.',
    status: 'Cold',
    updateStatus: 'Subnet isolation design meeting completed with CSI (₱40,000)',
    score: 45,
    createdAt: '2026-04-11T16:00:00.000Z',
    organizationId: 'org_18',
    productInterest: 'Lab Data Cabinets',
    streetAddress: '1800 Harbor Blvd',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_19',
    tenantId: 'tenant_demo',
    firstName: 'Arthur',
    lastName: 'Curry',
    customerType: 'Organization',
    companyName: 'Amnesty Bay Lighthouse',
    contactPerson: 'Arthur Curry',
    jobTitle: 'Lighthouse Keeper',
    email: 'acurry@amnestybay.com',
    phone: '(555) 011-2233',
    serviceRequired: 'Waterproof Cabling & Radio',
    leadSource: 'Web Form',
    estimatedValue: 15000,
    assignedUserId: 'user_sales_1',
    expectedCloseDate: '2026-05-20',
    notes: 'Needs weather-sealed network cabling to the mainland.',
    status: 'Warm',
    updateStatus: 'Waterproof fiber cabling sample dispatched (₱125,000)',
    score: 65,
    createdAt: '2026-04-12T13:30:00.000Z',
    organizationId: 'org_19',
    productInterest: 'Waterproof Cabling & Radio',
    streetAddress: '1900 Market St',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_20',
    tenantId: 'tenant_demo',
    firstName: 'Victor',
    lastName: 'Stone',
    customerType: 'Individual',
    companyName: '',
    contactPerson: 'Victor Stone',
    jobTitle: 'Student Athlete',
    email: 'vstone@gcu.edu',
    phone: '(555) 019-1122',
    serviceRequired: 'Smart Home Hub',
    leadSource: 'Referral',
    estimatedValue: 5000,
    assignedUserId: 'user_sales_2',
    expectedCloseDate: '2026-04-30',
    notes: 'Wants an integrated smart home setup with complete automation control from device.',
    status: 'Closed',
    updateStatus: 'Smart home IoT gateway successfully deployed (₱75,000)',
    score: 100,
    createdAt: '2026-04-13T09:00:00.000Z',
    streetAddress: '150 Grid Campus',
    productInterest: 'Smart Home Hub',
    city: 'Metropolis',
    province: 'NY',
  },
];
