import { Tenant, User, Contact, Deal, Pipeline, Workflow, Campaign, Template, Permission, RoleDefinition, Task, WorkflowExecution, ServiceOrder } from './types';

export const MOCK_TENANTS: Tenant[] = [
  {
    id: 'tenant_demo',
    name: 'Demo Corp Solutions',
    industry: 'IT Solutions',
    size: '50-200',
    email: 'contact@democorp.com',
    phone: '+1 (555) 123-4567',
    address: '123 Tech Lane, Silicon Valley, CA',
    status: 'active',
    approvalStep: 'completed',
    environment: 'production',
    createdAt: '2025-01-15T08:00:00.000Z',
  },
  {
    id: 'tenant_2',
    name: 'Global Logistics Inc.',
    industry: 'Logistics',
    size: '500+',
    email: 'info@globallogistics.com',
    phone: '+1 (555) 987-6543',
    address: '456 Freight Blvd, Chicago, IL',
    status: 'active',
    approvalStep: 'completed',
    environment: 'both',
    createdAt: '2025-02-20T10:30:00.000Z',
  },
  {
    id: 'tenant_3',
    name: 'NextGen Healthcare',
    industry: 'Healthcare',
    size: '200-500',
    email: 'partners@nextgenhealth.com',
    phone: '+1 (555) 456-7890',
    address: '789 Medical Parkway, Boston, MA',
    status: 'pending',
    approvalStep: 'basic',
    environment: 'none',
    createdAt: '2026-03-28T14:15:00.000Z',
  },
  {
    id: 'tenant_4',
    name: 'Starlight Media',
    industry: 'Media & Entertainment',
    size: '10-50',
    email: 'hello@starlightmedia.net',
    phone: '+1 (555) 234-5678',
    address: '321 Creative Studio, Austin, TX',
    status: 'suspended',
    approvalStep: 'completed',
    environment: 'production',
    createdAt: '2025-06-10T09:45:00.000Z',
  }
];

export const MOCK_USERS: User[] = [
  {
    id: 'user_super',
    tenantId: 'system',
    firstName: 'System',
    lastName: 'Admin',
    email: 'super@leadcrm.com',
    role: 'System Admin',
    status: 'active',
  },
  {
    id: 'user_client_admin',
    tenantId: 'tenant_demo',
    firstName: 'Alice',
    lastName: 'Admin',
    email: 'admin@democorp.com',
    role: 'Client Admin',
    status: 'active',
    team: 'Management',
  },
  {
    id: 'user_sales_1',
    tenantId: 'tenant_demo',
    firstName: 'Bob',
    lastName: 'Sales',
    email: 'bob@democorp.com',
    role: 'Sales Rep',
    status: 'active',
    team: 'Sales Team A',
  },
  {
    id: 'user_sales_2',
    tenantId: 'tenant_demo',
    firstName: 'Sarah',
    lastName: 'Jenkins',
    email: 'sarah.j@democorp.com',
    role: 'Sales Rep',
    status: 'active',
    team: 'Sales Team A',
  },
  {
    id: 'user_sales_3',
    tenantId: 'tenant_demo',
    firstName: 'Michael',
    lastName: 'Chen',
    email: 'm.chen@democorp.com',
    role: 'Sales Rep',
    status: 'active',
    team: 'Sales Team B',
  },
  {
    id: 'user_viewer_1',
    tenantId: 'tenant_demo',
    firstName: 'David',
    lastName: 'Manager',
    email: 'david.m@acmecorp.com',
    role: 'Viewer',
    status: 'pending',
    team: 'Management',
  },
  {
    id: 'user_guest',
    tenantId: 'tenant_demo',
    firstName: 'Guest',
    lastName: 'User',
    email: 'guest@democorp.com',
    role: 'Guest',
    status: 'active',
  }
];

export const MOCK_PIPELINES: Pipeline[] = [
  {
    id: 'pipe_sales',
    tenantId: 'tenant_demo',
    name: 'Sales Inquiries',
    stages: [
      { id: 'stage_lead', name: 'Discovery', order: 0 },
      { id: 'stage_assessment', name: 'Assessment', order: 1 },
      { id: 'stage_proposal', name: 'Proposal', order: 2 },
      { id: 'stage_negotiation', name: 'Negotiation', order: 3 },
      { id: 'stage_won', name: 'Closed Won', order: 4 },
      { id: 'stage_lost', name: 'Closed Lost', order: 5 },
    ]
  },
  {
    id: 'pipe_tech',
    tenantId: 'tenant_demo',
    name: 'Technical Support',
    stages: [
      { id: 'stage_ticket', name: 'Ticket Opened', order: 0 },
      { id: 'stage_review', name: 'Under Review', order: 1 },
      { id: 'stage_progress', name: 'In Progress', order: 2 },
      { id: 'stage_resolved', name: 'Resolved', order: 3 },
    ]
  },
  {
    id: 'pipe_project',
    tenantId: 'tenant_demo',
    name: 'Project Implementation',
    stages: [
      { id: 'stage_init', name: 'Initiation', order: 0 },
      { id: 'stage_plan', name: 'Planning', order: 1 },
      { id: 'stage_exec', name: 'Execution', order: 2 },
      { id: 'stage_handoff', name: 'Handoff', order: 3 },
    ]
  },
  {
    id: 'pipe_aftersales',
    tenantId: 'tenant_demo',
    name: 'After-sales Concerns',
    stages: [
      { id: 'stage_inquiry', name: 'Inquiry', order: 0 },
      { id: 'stage_followup', name: 'Follow-up', order: 1 },
      { id: 'stage_conclusion', name: 'Conclusion', order: 2 },
    ]
  }
];

export const MOCK_LEADS: Contact[] = [
  {
    id: 'lead_1',
    tenantId: 'tenant_demo',
    firstName: 'John',
    lastName: 'Doe',
    customerType: 'Organization',
    companyName: 'TechFlow Solutions',
    contactPerson: 'John Doe',
    jobTitle: 'CEO',
    email: 'john@techflow.com',
    phone: '(555) 010-1234',
    serviceRequired: 'CCTV Surveillance System',
    leadSource: 'Referral',
    estimatedValue: 85000,
    assignedUserId: 'user_sales_1',
    expectedCloseDate: '2026-05-15',
    notes: 'Looking to install 50 IP cameras across their new facility. High priority.',
    status: 'Hot',
    score: 95,
    createdAt: '2026-03-10T10:00:00.000Z',
    organizationId: 'org_1',
    productInterest: 'CCTV Surveillance System',
    streetAddress: '100 Tech Park Drive',
    city: 'Metropolis',
    province: 'NY'
  },
  {
    id: 'lead_2',
    tenantId: 'tenant_demo',
    firstName: 'Jane',
    lastName: 'Smith',
    customerType: 'Organization',
    companyName: 'Globex Corporation',
    contactPerson: 'Jane Smith',
    jobTitle: 'CTO',
    email: 'jane@globex.com',
    phone: '(555) 010-2345',
    serviceRequired: 'Structured Cabling',
    leadSource: 'LinkedIn',
    estimatedValue: 45000,
    assignedUserId: 'user_sales_2',
    expectedCloseDate: '2026-06-01',
    notes: 'Needs complete structured cabling for data and voice before Q3 move-in.',
    status: 'Warm',
    score: 75,
    createdAt: '2026-03-15T14:30:00.000Z',
    organizationId: 'org_2',
    productInterest: 'Structured Cabling',
    streetAddress: '200 Innovation Ave',
    city: 'Metropolis',
    province: 'NY'
  },
  {
    id: 'lead_3',
    tenantId: 'tenant_demo',
    firstName: 'Tony',
    lastName: 'Stark',
    customerType: 'Organization',
    companyName: 'Stark Industries',
    contactPerson: 'Tony Stark',
    jobTitle: 'Director of Engineering',
    email: 't.stark@starkind.com',
    phone: '(555) 010-3456',
    serviceRequired: 'Biometrics & Door Access',
    leadSource: 'Website',
    estimatedValue: 120000,
    assignedUserId: 'user_sales_3',
    expectedCloseDate: '2026-04-20',
    notes: 'Interested in smart locks and biometric access for their R&D labs.',
    status: 'Hot',
    score: 92,
    createdAt: '2026-03-20T09:15:00.000Z',
    organizationId: 'org_3',
    productInterest: 'Biometrics & Door Access',
    streetAddress: '300 Stark Tower',
    city: 'Metropolis',
    province: 'NY'
  },
  {
    id: 'lead_4',
    tenantId: 'tenant_demo',
    firstName: 'Bill',
    lastName: 'Lumbergh',
    customerType: 'Organization',
    companyName: 'Initech',
    contactPerson: 'Bill Lumbergh',
    jobTitle: 'VP Operations',
    email: 'bill@initech.com',
    phone: '(555) 010-4567',
    serviceRequired: 'Fire Detection and Alarm System',
    leadSource: 'Cold Call',
    estimatedValue: 15000,
    assignedUserId: 'user_sales_1',
    expectedCloseDate: '2026-07-10',
    notes: 'Just gathering information for next year budget. Needs FDAS compliance.',
    status: 'Cold',
    score: 35,
    createdAt: '2026-02-25T11:00:00.000Z',
    organizationId: 'org_4',
    productInterest: 'Fire Detection and Alarm System',
    streetAddress: '400 LexCorp Way',
    city: 'Metropolis',
    province: 'NY'
  },
  {
    id: 'lead_5',
    tenantId: 'tenant_demo',
    firstName: 'Albert',
    lastName: 'Wesker',
    customerType: 'Organization',
    companyName: 'Umbrella Corp',
    contactPerson: 'Albert Wesker',
    jobTitle: 'Head of Research',
    email: 'awesker@umbrella.com',
    phone: '(555) 010-5678',
    serviceRequired: 'Servers & Data Cabinets',
    leadSource: 'Conference',
    estimatedValue: 250000,
    assignedUserId: 'user_sales_2',
    expectedCloseDate: '2026-05-30',
    notes: 'Huge potential, looking for enterprise-grade servers and data cabinets.',
    status: 'Warm',
    score: 68,
    createdAt: '2026-03-05T16:45:00.000Z',
    organizationId: 'org_5',
    productInterest: 'Servers & Data Cabinets',
    streetAddress: '500 Aperture Lab',
    city: 'Metropolis',
    province: 'NY'
  },
  {
    id: 'lead_6',
    tenantId: 'tenant_demo',
    firstName: 'William',
    lastName: 'Bell',
    customerType: 'Organization',
    companyName: 'Massive Dynamic',
    contactPerson: 'William Bell',
    jobTitle: 'Founder',
    email: 'w.bell@massive.com',
    phone: '(555) 010-6789',
    serviceRequired: 'IP PBX & IP Phones',
    leadSource: 'Referral',
    estimatedValue: 75000,
    assignedUserId: 'user_sales_3',
    expectedCloseDate: '2026-04-15',
    notes: 'Ready to sign for new IP PBX system, just waiting on legal review.',
    status: 'Closed',
    score: 100,
    createdAt: '2026-01-10T10:20:00.000Z',
    organizationId: 'org_6',
    productInterest: 'IP PBX & IP Phones',
    streetAddress: '600 Cyberdine Sys',
    city: 'Metropolis',
    province: 'NY'
  },
  {
    id: 'lead_7',
    tenantId: 'tenant_demo',
    firstName: 'Robert',
    lastName: 'Thorn',
    customerType: 'Individual',
    companyName: '',
    contactPerson: 'Robert Thorn',
    jobTitle: 'Homeowner',
    email: 'r.thorn@private-life.com',
    phone: '(555) 010-7890',
    serviceRequired: 'Electric Fence & Perimeter Security',
    leadSource: 'Email Campaign',
    estimatedValue: 30000,
    assignedUserId: 'user_sales_1',
    expectedCloseDate: '2026-08-01',
    notes: 'Residential contact. Wants top-tier physical security and a secure electric fence around his primary estate.',
    status: 'Cancelled',
    score: 0,
    createdAt: '2026-02-01T13:10:00.000Z',
    streetAddress: '782 Woodlands Way, Sector 10',
    productInterest: 'Electric Fence & Perimeter Security',
    city: 'Metropolis',
    province: 'NY'
  },
  {
    id: 'lead_8',
    tenantId: 'tenant_demo',
    firstName: 'Miles',
    lastName: 'Dyson',
    customerType: 'Organization',
    companyName: 'Cyberdyne Systems',
    contactPerson: 'Miles Dyson',
    jobTitle: 'Director of Special Projects',
    email: 'm.dyson@cyberdyne.com',
    phone: '(555) 010-8901',
    serviceRequired: 'CCTV Surveillance System',
    leadSource: 'Referral',
    estimatedValue: 150000,
    assignedUserId: 'user_sales_1',
    expectedCloseDate: '2026-06-20',
    notes: 'Urgent requirement for high-security surveillance in the lab area.',
    status: 'Hot',
    score: 98,
    createdAt: '2026-04-01T10:00:00.000Z',
    organizationId: 'org_8',
    productInterest: 'CCTV Surveillance System',
    streetAddress: '800 Bugle St',
    city: 'Metropolis',
    province: 'NY'
  },
  {
    id: 'lead_9',
    tenantId: 'tenant_demo',
    firstName: 'Lucius',
    lastName: 'Fox',
    customerType: 'Organization',
    companyName: 'Wayne Enterprises',
    contactPerson: 'Lucius Fox',
    jobTitle: 'CEO',
    email: 'l.fox@wayneent.com',
    phone: '(555) 010-9012',
    serviceRequired: 'Structured Cabling',
    leadSource: 'Website',
    estimatedValue: 65000,
    assignedUserId: 'user_sales_2',
    expectedCloseDate: '2026-07-15',
    notes: 'Planning a major office expansion, needs full networking infrastructure.',
    status: 'Warm',
    score: 72,
    createdAt: '2026-04-02T14:30:00.000Z',
    organizationId: 'org_9',
    productInterest: 'Structured Cabling',
    streetAddress: '900 Planet Blvd',
    city: 'Metropolis',
    province: 'NY'
  },
  {
    id: 'lead_10',
    tenantId: 'tenant_demo',
    firstName: 'Norman',
    lastName: 'Osborn',
    customerType: 'Organization',
    companyName: 'Oscorp Industries',
    contactPerson: 'Norman Osborn',
    jobTitle: 'Chairman',
    email: 'n.osborn@oscorp.com',
    phone: '(555) 010-0123',
    serviceRequired: 'IP PBX & IP Phones',
    leadSource: 'Cold Call',
    estimatedValue: 25000,
    assignedUserId: 'user_sales_3',
    expectedCloseDate: '2026-09-01',
    notes: 'Initial inquiry about upgrading their legacy phone system.',
    status: 'Cold',
    score: 28,
    createdAt: '2026-04-03T09:15:00.000Z',
    organizationId: 'org_10',
    productInterest: 'IP PBX & IP Phones',
    streetAddress: '1000 Amazon St',
    city: 'Metropolis',
    province: 'NY'
  },
  {
    id: 'lead_11',
    tenantId: 'tenant_demo',
    firstName: 'Lex',
    lastName: 'Luthor',
    customerType: 'Organization',
    companyName: 'LexCorp',
    contactPerson: 'Lex Luthor',
    jobTitle: 'CEO',
    email: 'lex@lexcorp.com',
    phone: '(555) 010-1234',
    serviceRequired: 'Biometrics & Door Access',
    leadSource: 'LinkedIn',
    estimatedValue: 180000,
    assignedUserId: 'user_sales_2',
    expectedCloseDate: '2026-05-30',
    notes: 'Requires state-of-the-art biometric security for their main tower.',
    status: 'Hot',
    score: 94,
    createdAt: '2026-04-04T11:00:00.000Z',
    organizationId: 'org_11',
    productInterest: 'Biometrics & Door Access',
    streetAddress: '1100 Silicon Blvd',
    city: 'Metropolis',
    province: 'NY'
  },
  {
    id: 'lead_12',
    tenantId: 'tenant_demo',
    firstName: 'Cave',
    lastName: 'Johnson',
    customerType: 'Organization',
    companyName: 'Aperture Science',
    contactPerson: 'Cave Johnson',
    jobTitle: 'Founder',
    email: 'cave@aperture.com',
    phone: '(555) 010-2345',
    serviceRequired: 'Servers & Data Cabinets',
    leadSource: 'Conference',
    estimatedValue: 300000,
    assignedUserId: 'user_sales_1',
    expectedCloseDate: '2026-08-15',
    notes: 'Looking for robust server solutions for their testing facilities.',
    status: 'Warm',
    score: 65,
    createdAt: '2026-04-05T16:45:00.000Z',
    organizationId: 'org_12',
    productInterest: 'Servers & Data Cabinets',
    streetAddress: '1200 Enterprise Rd',
    city: 'Metropolis',
    province: 'NY'
  },
  {
    id: 'lead_13',
    tenantId: 'tenant_demo',
    firstName: 'Sarah',
    lastName: 'Connor',
    customerType: 'Individual',
    companyName: '',
    contactPerson: 'Sarah Connor',
    jobTitle: 'Private Resident',
    email: 'sconnor@cyber-survive.org',
    phone: '(555) 010-9944',
    serviceRequired: 'High-Definition CCTV Coverage',
    leadSource: 'Referral',
    estimatedValue: 18000,
    assignedUserId: 'user_sales_3',
    expectedCloseDate: '2026-05-02',
    notes: 'Extremely focused on zero blind-spots around her residence. Requires night-vision cams.',
    status: 'Hot',
    score: 95,
    createdAt: '2026-04-06T08:30:00.000Z',
    streetAddress: '404 Hidden Valley Road',
    productInterest: 'High-Definition CCTV Coverage',
    city: 'Metropolis',
    province: 'NY'
  },
  {
    id: 'lead_14',
    tenantId: 'tenant_demo',
    firstName: 'Bruce',
    lastName: 'Wayne',
    customerType: 'Individual',
    companyName: '',
    contactPerson: 'Bruce Wayne',
    jobTitle: 'Private Resident',
    email: 'bwayne@wayne-estate.com',
    phone: '(555) 010-9000',
    serviceRequired: 'Intrusion Detection System',
    leadSource: 'Referral',
    estimatedValue: 89000,
    assignedUserId: 'user_sales_2',
    expectedCloseDate: '2026-06-10',
    notes: 'Wants specialized subterranean motion detectors and thermal cameras installed around private property lines.',
    status: 'Hot',
    score: 99,
    createdAt: '2026-04-07T14:00:00.000Z',
    streetAddress: '1007 Mountain Crest Blvd',
    productInterest: 'Intrusion Detection System',
    city: 'Metropolis',
    province: 'NY'
  },
  {
    id: 'lead_15',
    tenantId: 'tenant_demo',
    firstName: 'Peter',
    lastName: 'Parker',
    customerType: 'Individual',
    companyName: '',
    contactPerson: 'Peter Parker',
    jobTitle: 'Freelance Photographer',
    email: 'pparker@dailybugle.net',
    phone: '(555) 012-3498',
    serviceRequired: 'Basic Home Assessment',
    leadSource: 'Web Form',
    estimatedValue: 1200,
    assignedUserId: 'user_sales_3',
    expectedCloseDate: '2026-05-15',
    notes: 'Needs simple door access logs and smart lock for apartment.',
    status: 'Warm',
    score: 60,
    createdAt: '2026-04-08T10:00:00.000Z',
    streetAddress: '20 Ingram St, Queens',
    productInterest: 'Basic Home Assessment',
    city: 'Metropolis',
    province: 'NY'
  },
  {
    id: 'lead_16',
    tenantId: 'tenant_demo',
    firstName: 'Clark',
    lastName: 'Kent',
    customerType: 'Organization',
    companyName: 'Daily Planet',
    contactPerson: 'Clark Kent',
    jobTitle: 'Investigative Journalist',
    email: 'ckent@dailyplanet.com',
    phone: '(555) 013-4455',
    serviceRequired: 'High-speed Network Routing',
    leadSource: 'Referral',
    estimatedValue: 55000,
    assignedUserId: 'user_sales_1',
    expectedCloseDate: '2026-06-01',
    notes: 'Upgrading the printing press and editorial floor network.',
    status: 'Hot',
    score: 85,
    createdAt: '2026-04-09T09:15:00.000Z',
    organizationId: 'org_16',
    productInterest: 'High-speed Network Routing',
    streetAddress: '1600 Business Ctr',
    city: 'Metropolis',
    province: 'NY'
  },
  {
    id: 'lead_17',
    tenantId: 'tenant_demo',
    firstName: 'Diana',
    lastName: 'Prince',
    customerType: 'Organization',
    companyName: 'Themyscira Antiquities',
    contactPerson: 'Diana Prince',
    jobTitle: 'Curator',
    email: 'dprince@antiquities.org',
    phone: '(555) 018-9999',
    serviceRequired: 'Museum Security System',
    leadSource: 'Social Media Advertisement',
    estimatedValue: 210000,
    assignedUserId: 'user_sales_2',
    expectedCloseDate: '2026-07-20',
    notes: 'Requires artifact-level vibration sensors, glass-break detectors, and round-the-clock monitoring integration.',
    status: 'Hot',
    score: 97,
    createdAt: '2026-04-10T11:45:00.000Z',
    organizationId: 'org_17',
    productInterest: 'Museum Security System',
    streetAddress: '1700 Industrial Ave',
    city: 'Metropolis',
    province: 'NY'
  },
  {
    id: 'lead_18',
    tenantId: 'tenant_demo',
    firstName: 'Barry',
    lastName: 'Allen',
    customerType: 'Organization',
    companyName: 'Central City PD',
    contactPerson: 'Barry Allen',
    jobTitle: 'CSI Forensics',
    email: 'ballen@ccpd.gov',
    phone: '(555) 019-8877',
    serviceRequired: 'Lab Data Cabinets',
    leadSource: 'Cold Call',
    estimatedValue: 40000,
    assignedUserId: 'user_sales_3',
    expectedCloseDate: '2026-05-30',
    notes: 'Expanding the forensic labs, needs isolated subnet and secured data cabinets.',
    status: 'Cold',
    score: 45,
    createdAt: '2026-04-11T16:00:00.000Z',
    organizationId: 'org_18',
    productInterest: 'Lab Data Cabinets',
    streetAddress: '1800 Harbor Blvd',
    city: 'Metropolis',
    province: 'NY'
  },
  {
    id: 'lead_19',
    tenantId: 'tenant_demo',
    firstName: 'Arthur',
    lastName: 'Curry',
    customerType: 'Organization',
    companyName: 'Amnesty Bay Lighthouse',
    contactPerson: 'Arthur Curry',
    jobTitle: 'Lighthouse Keeper',
    email: 'acurry@amnestybay.com',
    phone: '(555) 011-2233',
    serviceRequired: 'Waterproof Cabling & Radio',
    leadSource: 'Web Form',
    estimatedValue: 15000,
    assignedUserId: 'user_sales_1',
    expectedCloseDate: '2026-05-20',
    notes: 'Needs weather-sealed network cabling to the mainland.',
    status: 'Warm',
    score: 65,
    createdAt: '2026-04-12T13:30:00.000Z',
    organizationId: 'org_19',
    productInterest: 'Waterproof Cabling & Radio',
    streetAddress: '1900 Market St',
    city: 'Metropolis',
    province: 'NY'
  },
  {
    id: 'lead_20',
    tenantId: 'tenant_demo',
    firstName: 'Victor',
    lastName: 'Stone',
    customerType: 'Individual',
    companyName: '',
    contactPerson: 'Victor Stone',
    jobTitle: 'Student Athlete',
    email: 'vstone@gcu.edu',
    phone: '(555) 019-1122',
    serviceRequired: 'Smart Home Hub',
    leadSource: 'Referral',
    estimatedValue: 5000,
    assignedUserId: 'user_sales_2',
    expectedCloseDate: '2026-04-30',
    notes: 'Wants an integrated smart home setup with complete automation control from device.',
    status: 'Closed',
    score: 100,
    createdAt: '2026-04-13T09:00:00.000Z',
    streetAddress: '150 Grid Campus',
    productInterest: 'Smart Home Hub',
    city: 'Metropolis',
    province: 'NY'
  }
];

export const MOCK_DEALS: Deal[] = [
  {
    id: 'deal_1',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_proposal',
    title: 'Office Building CCTV System',
    companyName: 'Innovate Solutions',
    contactPerson: 'Sarah Johnson',
    value: 85000,
    priority: 'High',
    expectedCloseDate: '2026-05-15',
    description: '50-camera surveillance system for corporate headquarters',
    assignedUserId: 'user_sales_2',
    order: 0,
    createdAt: '2026-03-12T10:00:00.000Z',
    history: [
      { stageId: 'stage_lead', timestamp: '2026-03-12T10:00:00.000Z', userId: 'user_sales_2', note: 'Deal created' },
      { stageId: 'stage_assessment', timestamp: '2026-03-14T11:30:00.000Z', userId: 'user_sales_2', note: 'Completed site inspection' },
      { stageId: 'stage_proposal', timestamp: '2026-03-18T09:00:00.000Z', userId: 'user_sales_2', note: 'Proposal sent to customer' }
    ]
  },
  {
    id: 'deal_2',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_negotiation',
    title: 'Biometric Access Control',
    companyName: 'Nexus Digital',
    contactPerson: 'Robert Taylor',
    value: 68000,
    priority: 'Medium',
    expectedCloseDate: '2026-04-25',
    description: 'Fingerprint and card-based access for 50 doors',
    assignedUserId: 'user_sales_1',
    order: 1,
    createdAt: '2026-03-18T14:30:00.000Z',
    history: [
      { stageId: 'stage_lead', timestamp: '2026-03-18T14:30:00.000Z', userId: 'user_sales_1', note: 'Deal created' },
      { stageId: 'stage_assessment', timestamp: '2026-03-20T10:00:00.000Z', userId: 'user_sales_1' },
      { stageId: 'stage_proposal', timestamp: '2026-03-22T15:45:00.000Z', userId: 'user_sales_1' },
      { stageId: 'stage_negotiation', timestamp: '2026-03-25T10:00:00.000Z', userId: 'user_sales_1' }
    ]
  },
  {
    id: 'deal_3',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_project',
    stageId: 'stage_proposal',
    title: 'Enterprise WiFi Infrastructure',
    companyName: 'TechCorp Inc',
    contactPerson: 'John Smith',
    value: 125000,
    priority: 'High',
    expectedCloseDate: '2026-04-30',
    description: 'Complete WiFi 6E deployment for 10-floor office building',
    assignedUserId: 'user_sales_3',
    order: 0,
    createdAt: '2026-03-22T09:15:00.000Z',
    history: [
      { stageId: 'stage_lead', timestamp: '2026-03-22T09:15:00.000Z', userId: 'user_sales_3', note: 'Deal created' },
      { stageId: 'stage_assessment', timestamp: '2026-03-24T14:00:00.000Z', userId: 'user_sales_3' },
      { stageId: 'stage_proposal', timestamp: '2026-03-26T11:00:00.000Z', userId: 'user_sales_3' }
    ]
  },
  {
    id: 'deal_lost_1',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_lost',
    title: 'Server & Data Cabinet Upgrade',
    companyName: 'OldTech Solutions',
    contactPerson: 'Arthur Dent',
    value: 15000,
    priority: 'Low',
    expectedCloseDate: '2026-03-20',
    description: 'Upgrade of legacy servers and data cabinets.',
    assignedUserId: 'user_sales_1',
    lostReason: 'Budget was cut due to internal restructuring.',
    order: 0,
    createdAt: '2026-02-15T14:00:00.000Z',
    history: [
      { stageId: 'stage_lead', timestamp: '2026-02-15T14:00:00.000Z', userId: 'user_sales_1', note: 'Deal created' },
      { stageId: 'stage_proposal', timestamp: '2026-02-20T10:00:00.000Z', userId: 'user_sales_1' },
      { stageId: 'stage_lost', timestamp: '2026-03-01T15:00:00.000Z', userId: 'user_sales_1', note: 'Budget was cut due to internal restructuring.' }
    ]
  },
  {
    id: 'deal_4',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_project',
    stageId: 'stage_assessment',
    title: 'IP PBX System Installation',
    companyName: 'DataWorks',
    contactPerson: 'Michael Chen',
    value: 45000,
    priority: 'Medium',
    expectedCloseDate: '2026-05-10',
    description: 'IPBX and IP Phones for new branch office',
    assignedUserId: 'user_sales_3',
    order: 0,
    createdAt: '2026-03-25T16:45:00.000Z',
    history: [
      { stageId: 'stage_lead', timestamp: '2026-03-25T16:45:00.000Z', userId: 'user_sales_3', note: 'Contact created' },
      { stageId: 'stage_assessment', timestamp: '2026-03-26T10:00:00.000Z', userId: 'user_sales_3', note: 'Network assessment started' }
    ]
  },
  {
    id: 'deal_5',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_won',
    title: 'Corporate Laptop Fleet',
    companyName: 'CloudNine Systems',
    contactPerson: 'Emily Davis',
    value: 120000,
    priority: 'High',
    expectedCloseDate: '2026-03-10',
    description: 'Procurement of 100 high-performance laptops for engineering team',
    assignedUserId: 'user_sales_2',
    order: 0,
    createdAt: '2026-02-01T09:00:00.000Z',
    history: [
      { stageId: 'stage_lead', timestamp: '2026-02-01T09:00:00.000Z', userId: 'user_sales_2' },
      { stageId: 'stage_proposal', timestamp: '2026-02-05T11:00:00.000Z', userId: 'user_sales_2' },
      { stageId: 'stage_proposal', timestamp: '2026-02-15T14:00:00.000Z', userId: 'user_sales_2' },
      { stageId: 'stage_negotiation', timestamp: '2026-02-25T10:00:00.000Z', userId: 'user_sales_2' },
      { stageId: 'stage_won', timestamp: '2026-03-10T15:30:00.000Z', userId: 'user_sales_2', note: 'Contract signed' }
    ]
  }
];

export const MOCK_WORKFLOWS: Workflow[] = [
  {
    id: 'wf_1',
    tenantId: 'tenant_demo',
    name: 'CCTV Site Survey',
    description: 'Automatically schedule a site survey when a CCTV deal is qualified.',
    category: 'Security',
    status: 'active',
    trigger: 'deal_stage_qualified',
    condition: 'title_contains_CCTV',
    actions: [{ id: 'action_1', type: 'create_task', config: { taskTitle: 'Schedule Site Survey', taskDescription: 'Please schedule a site survey for this CCTV deal.' } }],
    executionCount: 24,
  },
  {
    id: 'wf_2',
    tenantId: 'tenant_demo',
    name: 'Biometrics Config',
    description: 'Assign a configuration task to the IT team when a Biometrics deal is won.',
    category: 'Security',
    status: 'active',
    trigger: 'deal_stage_won',
    condition: 'title_contains_Biometrics',
    actions: [{ id: 'action_1', type: 'create_task', config: { taskTitle: 'Configure Biometrics', taskDescription: 'Please configure the biometrics system for this won deal.' } }],
    executionCount: 12,
  },
  {
    id: 'wf_3',
    tenantId: 'tenant_demo',
    name: 'Structured Cabling Layout',
    description: 'Generate a cabling layout task when a networking deal reaches proposal stage.',
    category: 'Telecom',
    status: 'active',
    trigger: 'deal_stage_proposal',
    condition: 'title_contains_Cabling',
    actions: [{ id: 'action_1', type: 'create_task', config: { taskTitle: 'Generate Cabling Layout', taskDescription: 'Create a structured cabling layout for this proposal.' } }],
    executionCount: 8,
  },
  {
    id: 'wf_4',
    tenantId: 'tenant_demo',
    name: 'Server Provisioning',
    description: 'Notify the hardware team to prepare servers when an IT deal is won.',
    category: 'IT',
    status: 'active',
    trigger: 'deal_stage_won',
    condition: 'title_contains_Server',
    actions: [{ id: 'action_1', type: 'send_email', config: { templateId: 'tpl_1' } }],
    executionCount: 5,
  },
  {
    id: 'wf_5',
    tenantId: 'tenant_demo',
    name: 'New Contact Welcome',
    description: 'Send a welcome email to all new contacts.',
    category: 'General',
    status: 'active',
    trigger: 'lead_created',
    actions: [{ id: 'action_1', type: 'send_email', config: { templateId: 'tpl_2' } }],
    executionCount: 142,
  }
];

export const MOCK_SERVICE_ORDERS: ServiceOrder[] = [
  {
    id: 'so1',
    tenantId: 't1',
    title: 'Install 4 CCTV Cameras',
    description: 'Install and configure 4 IP cameras at the main entrance and lobby.',
    clientName: 'Acme Corp',
    address: '123 Tech Blvd, Silicon Valley, CA',
    status: 'pending',
    assignedTechnicianId: 'u4', // We'll assume u4 is a technician
    scheduledDate: new Date().toISOString(),
    photos: {},
    createdAt: new Date().toISOString(),
  },
  {
    id: 'so2',
    tenantId: 't1',
    title: 'Network Rack Cable Management',
    description: 'Clean up and organize cables in the main server room rack.',
    clientName: 'Global Industries',
    address: '456 Enterprise Way, New York, NY',
    status: 'in-progress',
    assignedTechnicianId: 'u4',
    scheduledDate: new Date().toISOString(),
    photos: {
      before: ['https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=400'],
    },
    createdAt: new Date().toISOString(),
  }
];

export const MOCK_TASKS: Task[] = [
  {
    id: 'task_1',
    tenantId: 'tenant_demo',
    dealId: 'deal_1',
    title: 'Initial Site Survey',
    description: 'Conduct a physical survey of the client site for CCTV placement and cable pathing.',
    status: 'completed',
    dueDate: '2026-03-15',
    assignedUserId: 'user_sales_2',
    createdAt: '2026-03-12T10:00:00.000Z',
    priority: 'Medium',
  },
  {
    id: 'task_2',
    tenantId: 'tenant_demo',
    dealId: 'deal_3',
    title: 'Proposal Review',
    description: 'Review the enterprise solution proposal with the legal team and regional stakeholders.',
    status: 'pending',
    dueDate: '2026-04-05',
    assignedUserId: 'user_sales_3',
    createdAt: '2026-03-22T09:15:00.000Z',
    priority: 'High',
  },
  {
    id: 'task_3',
    tenantId: 'tenant_demo',
    title: 'Hardware Order Placement',
    description: 'Execute procurement order for fiber switches, network cables, and router modules.',
    status: 'in-progress',
    dueDate: '2026-06-15',
    assignedUserId: 'user_sales_2',
    createdAt: '2026-05-25T11:00:00.000Z',
    priority: 'High',
  },
  {
    id: 'task_4',
    tenantId: 'tenant_demo',
    title: 'Draft User Manual',
    description: 'Create draft user manuals and handbook guides for custom VoIP lines configuration.',
    status: 'pending',
    dueDate: '2026-06-30',
    assignedUserId: 'user_sales_1',
    createdAt: '2026-05-28T14:30:00.000Z',
    priority: 'Low',
  }
];

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp_1',
    tenantId: 'tenant_demo',
    name: 'Q1 Security Upgrade Promo',
    description: 'Special offers on CCTV and Biometrics upgrades',
    type: 'Email',
    status: 'active',
    targetAudience: 'Existing Customers',
    sentCount: 1250,
    openedCount: 845,
    clickedCount: 234,
    engagement: 90,
    createdAt: '2/1/2026',
  },
  {
    id: 'camp_2',
    tenantId: 'tenant_demo',
    name: 'Telecom Infrastructure Audit',
    type: 'Sms',
    status: 'completed',
    targetAudience: 'Enterprise Contacts',
    sentCount: 580,
    engagement: 15,
    createdAt: '1/10/2026',
  },
  {
    id: 'camp_3',
    tenantId: 'tenant_demo',
    name: 'Webinar: Modern Data Cabinets',
    description: 'Join Us: Best Practices for Server Room Organization',
    type: 'Multi-Channel',
    status: 'scheduled',
    targetAudience: 'IT Managers',
    sentCount: 0,
    engagement: 0,
    createdAt: '2/14/2026',
  },
  {
    id: 'camp_4',
    tenantId: 'tenant_demo',
    name: 'Holiday Special Offer',
    description: '🎉 Exclusive Holiday Deal - 30% Off Installation',
    type: 'Email',
    status: 'paused',
    targetAudience: 'All Contacts',
    sentCount: 450,
    openedCount: 198,
    clickedCount: 67,
    engagement: 59,
    createdAt: '2/12/2026',
  }
];

export const MOCK_TEMPLATES: Template[] = [
  {
    id: 'tpl_1',
    tenantId: 'tenant_demo',
    name: 'Welcome Email',
    type: 'Email',
    category: 'Onboarding',
    subject: 'Welcome to Camxian Technologies!',
    content: 'Hi {{first_name}}, Welcome aboard! We\'re thrilled to provide you with top-tier security and IT solutions...',
  },
  {
    id: 'tpl_2',
    tenantId: 'tenant_demo',
    name: 'Security Audit Offer',
    type: 'Email',
    category: 'Marketing',
    subject: 'Free Security Audit for {{company_name}}',
    content: 'Dear {{first_name}}, We\'re offering a complimentary security audit for your premises...',
  },
  {
    id: 'tpl_3',
    tenantId: 'tenant_demo',
    name: 'Follow-up',
    type: 'Email',
    category: 'Sales',
    subject: 'Following up on our conversation',
    content: 'Hi {{first_name}}, Thank you for taking the time to speak with us about your infrastructure needs...',
  },
  {
    id: 'tpl_4',
    tenantId: 'tenant_demo',
    name: 'Site Survey Reminder',
    type: 'SMS',
    category: 'Reminder',
    content: 'Hi {{first_name}}, this is a reminder about your site survey on {{date}} at {{time}}.',
  },
  {
    id: 'tpl_5',
    tenantId: 'tenant_demo',
    name: 'Proposal Update',
    type: 'SMS',
    category: 'Sales',
    content: 'Great news! Your proposal has been approved. Contact us to get started: {{phone}}',
  },
  {
    id: 'tpl_6',
    tenantId: 'tenant_demo',
    name: 'Quick Check-in',
    type: 'SMS',
    category: 'Support',
    content: 'Hi {{first_name}}! Just checking in. Any questions about your new installation? Reply or call {{phone}}',
  }
];

export const MOCK_PERMISSIONS: Permission[] = [
  { id: 'p1', name: 'View Dashboard', category: 'Dashboard', description: 'Access to the main dashboard' },
  { id: 'p2', name: 'View All Contacts', category: 'Contacts', description: 'View all contact lists across the organization' },
  { id: 'p2_own', name: 'View Own Contacts', category: 'Contacts', description: 'View only assigned contacts' },
  { id: 'p3', name: 'Create Contacts', category: 'Contacts', description: 'Add new contacts' },
  { id: 'p4', name: 'Edit All Contacts', category: 'Contacts', description: 'Modify any existing contacts' },
  { id: 'p4_own', name: 'Edit Own Contacts', category: 'Contacts', description: 'Modify only assigned contacts' },
  { id: 'p5', name: 'Delete All Contacts', category: 'Contacts', description: 'Remove any contacts' },
  { id: 'p5_own', name: 'Delete Own Contacts', category: 'Contacts', description: 'Remove only assigned contacts' },
  { id: 'p6', name: 'Export Contacts', category: 'Contacts', description: 'Export contacts to CSV' },
  { id: 'p7', name: 'View All Deals', category: 'Deals', description: 'View all deal pipelines across the organization' },
  { id: 'p7_own', name: 'View Own Deals', category: 'Deals', description: 'View only assigned deals' },
  { id: 'p8', name: 'Create Deals', category: 'Deals', description: 'Add new deals' },
  { id: 'p9', name: 'Edit All Deals', category: 'Deals', description: 'Modify any existing deals' },
  { id: 'p9_own', name: 'Edit Own Deals', category: 'Deals', description: 'Modify only assigned deals' },
  { id: 'p10', name: 'Delete All Deals', category: 'Deals', description: 'Remove any deals' },
  { id: 'p10_own', name: 'Delete Own Deals', category: 'Deals', description: 'Remove only assigned deals' },
  { id: 'p11', name: 'Manage Pipelines', category: 'Deals', description: 'Configure pipeline stages' },
  { id: 'p12', name: 'View Workflows', category: 'Workflows', description: 'View automation workflows' },
  { id: 'p13', name: 'Create Workflows', category: 'Workflows', description: 'Add new workflows' },
  { id: 'p14', name: 'Edit Workflows', category: 'Workflows', description: 'Modify existing workflows' },
  { id: 'p15', name: 'Delete Workflows', category: 'Workflows', description: 'Remove workflows' },
  { id: 'p16', name: 'Execute Workflows', category: 'Workflows', description: 'Manually run workflows' },
  { id: 'p17', name: 'View Campaigns', category: 'Campaigns', description: 'View marketing campaigns' },
  { id: 'p18', name: 'Create Campaigns', category: 'Campaigns', description: 'Add new campaigns' },
  { id: 'p19', name: 'Edit Campaigns', category: 'Campaigns', description: 'Modify existing campaigns' },
  { id: 'p20', name: 'Delete Campaigns', category: 'Campaigns', description: 'Remove campaigns' },
  { id: 'p21', name: 'Send Campaigns', category: 'Campaigns', description: 'Trigger campaign delivery' },
  { id: 'p22', name: 'View Users', category: 'Users', description: 'View team members' },
  { id: 'p23', name: 'Create Users', category: 'Users', description: 'Add new team members' },
  { id: 'p24', name: 'Edit Users', category: 'Users', description: 'Modify user details' },
  { id: 'p25', name: 'Delete Users', category: 'Users', description: 'Remove team members' },
  { id: 'p26', name: 'Manage Roles', category: 'Users', description: 'Configure roles and permissions' },
  { id: 'p27', name: 'View Settings', category: 'Settings', description: 'Access organization settings' },
  { id: 'p28', name: 'Edit Settings', category: 'Settings', description: 'Modify organization settings' },
  { id: 'p29', name: 'Manage Billing', category: 'Settings', description: 'View and pay invoices' },
  { id: 'p30', name: 'View Audit Logs', category: 'Settings', description: 'Access system activity logs' },
  { id: 'p31', name: 'View Reports', category: 'Reports', description: 'Access analytics reports' },
  { id: 'p32', name: 'Create Reports', category: 'Reports', description: 'Build custom reports' },
  { id: 'p33', name: 'Export Reports', category: 'Reports', description: 'Export report data' },
  { id: 'p34', name: 'Manage Dashboard', category: 'Dashboard', description: 'Customize dashboard layout and widgets' },
  { id: 'p35', name: 'View Inventory', category: 'Inventory', description: 'View stock and inventory levels' },
  { id: 'p36', name: 'Manage Inventory', category: 'Inventory', description: 'Add, edit, or delete inventory items' },
  { id: 'p37', name: 'View Assets', category: 'Assets', description: 'View installed client assets' },
  { id: 'p38', name: 'Manage Assets', category: 'Assets', description: 'Register or modify client assets' },
];

export const MOCK_ROLES: RoleDefinition[] = [
  {
    id: 'r1',
    tenantId: 'tenant_demo',
    name: 'Administrator',
    description: 'Full system access with all permissions',
    isSystemRole: true,
    userCount: 2,
    permissions: MOCK_PERMISSIONS.map(p => p.id),
    updatedAt: '1/1/2026'
  },
  {
    id: 'r_tech',
    tenantId: 'tenant_demo',
    name: 'Technician',
    description: 'Field technician with access to service orders and assets',
    isSystemRole: true,
    userCount: 5,
    permissions: ['p1', 'p37', 'p38'],
    updatedAt: '1/1/2026'
  },
  {
    id: 'r2',
    tenantId: 'tenant_demo',
    name: 'Sales Manager',
    description: 'Manage sales operations, contacts, deals, and campaigns',
    isSystemRole: true,
    userCount: 3,
    permissions: ['p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10', 'p12', 'p16', 'p17', 'p18', 'p19', 'p21', 'p22', 'p31', 'p32', 'p33'],
    updatedAt: '1/1/2026'
  },
  {
    id: 'r3',
    tenantId: 'tenant_demo',
    name: 'Sales Representative',
    description: 'Create and manage own contacts and deals',
    isSystemRole: true,
    userCount: 8,
    permissions: ['p1', 'p2_own', 'p3', 'p4_own', 'p7_own', 'p8', 'p9_own', 'p12', 'p17', 'p31'],
    updatedAt: '1/1/2026'
  },
  {
    id: 'r4',
    tenantId: 'tenant_demo',
    name: 'Support Agent',
    description: 'Handle support tickets and customer inquiries',
    isSystemRole: true,
    userCount: 5,
    permissions: ['p1', 'p2', 'p4', 'p7', 'p8', 'p9', 'p12', 'p17'],
    updatedAt: '1/1/2026'
  },
  {
    id: 'r5',
    tenantId: 'tenant_demo',
    name: 'Marketing Manager',
    description: 'Manage marketing campaigns and workflows',
    isSystemRole: true,
    userCount: 2,
    permissions: ['p1', 'p2', 'p6', 'p7', 'p12', 'p13', 'p14', 'p16', 'p17', 'p18', 'p19', 'p20', 'p21', 'p31', 'p32', 'p33'],
    updatedAt: '1/1/2026'
  },
  {
    id: 'r6',
    tenantId: 'tenant_demo',
    name: 'Viewer',
    description: 'Read-only access to most modules',
    isSystemRole: true,
    userCount: 3,
    permissions: ['p1', 'p2', 'p7', 'p12', 'p17', 'p31'],
    updatedAt: '1/1/2026'
  },
  {
    id: 'r12',
    tenantId: 'tenant_demo',
    name: 'Executive',
    description: 'High-level overview of organization performance and reports',
    isSystemRole: true,
    userCount: 1,
    permissions: ['p1', 'p2', 'p7', 'p12', 'p17', 'p22', 'p27', 'p30', 'p31', 'p33'],
    updatedAt: '4/3/2026'
  },
  {
    id: 'r13',
    tenantId: 'tenant_demo',
    name: 'Billing Manager',
    description: 'Manage organization billing, invoices, and settings',
    isSystemRole: true,
    userCount: 1,
    permissions: ['p1', 'p27', 'p28', 'p29', 'p30'],
    updatedAt: '4/3/2026'
  },
  {
    id: 'r14',
    tenantId: 'tenant_demo',
    name: 'Customer Success',
    description: 'Manage customer relationships, onboarding, and retention',
    isSystemRole: true,
    userCount: 2,
    permissions: ['p1', 'p2', 'p3', 'p4', 'p7', 'p12', 'p16', 'p31'],
    updatedAt: '4/3/2026'
  },
  {
    id: 'r15',
    tenantId: 'tenant_demo',
    name: 'Guest',
    description: 'Read-only demo access',
    isSystemRole: true,
    userCount: 1,
    permissions: ['p1', 'p2', 'p7', 'p12', 'p17'],
    updatedAt: '4/5/2026'
  }
];

export const MOCK_WORKFLOW_EXECUTIONS: WorkflowExecution[] = [
  {
    id: 'exec_1',
    workflowId: 'wf_1',
    tenantId: 'tenant_demo',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    status: 'success',
    details: 'Created task: CCTV Site Survey',
    relatedEntityId: 'deal_1'
  },
  {
    id: 'exec_2',
    workflowId: 'wf_2',
    tenantId: 'tenant_demo',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    status: 'success',
    details: 'Sent Email using template: Proposal Follow-up',
    relatedEntityId: 'deal_2'
  }
];

export const MOCK_ASSETS: any[] = [
  {
    id: 'AST-5001',
    tenantId: 'tenant_demo',
    name: 'Hikvision 4K IP Camera',
    category: 'Security',
    serialNumber: 'HKV-99283-X1',
    client: 'SM City North EDSA',
    status: 'Active',
    installDate: '2025-12-10',
    warrantyExpiry: '2027-12-10',
    location: 'Main Entrance - Gate 1'
  },
  {
    id: 'AST-5002',
    tenantId: 'tenant_demo',
    name: 'Cisco Catalyst 9200 Switch',
    category: 'IT',
    serialNumber: 'CSCO-SW-8821',
    client: 'Ayala Malls Vertis North',
    status: 'Active',
    installDate: '2026-01-15',
    warrantyExpiry: '2029-01-15',
    location: 'Server Room - Rack A'
  }
];

export const MOCK_INVENTORY: any[] = [
  {
    id: 'INV-1001',
    tenantId: 'tenant_demo',
    name: 'Cat6 Ethernet Cable (305m)',
    sku: 'CAB-CAT6-305',
    category: 'Telecom',
    quantity: 45,
    minQuantity: 10,
    unitPrice: 120,
    supplier: 'Belden Philippines',
    lastRestocked: '2026-03-15'
  },
  {
    id: 'INV-1002',
    tenantId: 'tenant_demo',
    name: 'IP Camera 4MP Dome',
    sku: 'CAM-IP-4MP-D',
    category: 'Security',
    quantity: 12,
    minQuantity: 5,
    unitPrice: 85,
    supplier: 'Hikvision Distributor',
    lastRestocked: '2026-03-20'
  }
];
