'use client';
import { useState } from 'react';
import { Plus, ArrowUp, ArrowDown } from 'lucide-react';
import { CLOSING_FIELD_TYPES, ClosingFieldInputSchema, CUSTOM_FIELD_MODULES, CUSTOM_FIELD_MODULE_LABELS, CLOSED_WON_GROUP_ID, defaultFieldLayout, getCrmFieldCatalog, isClosedWonField, normalizeCustomField, type CustomFieldModule, type ClosingField, type ClosingFieldInput, type FieldLayout, type CrmFieldCatalogEntry } from '@leadcrm/shared';
import { apiClient } from '@/lib/api/client';
import { useCachedPage } from '@/shared/hooks/use-cached-page';
import { useHasPermission } from '@/shared/hooks/use-permissions';
import { PageHeader } from '@/shared/components/ui/page-header';
import { panelBodyClass, panelFooterClass, panelInputClass } from '@/shared/components/side-panel-styles';
import { SlidingDrawer } from '@/shared/components/sliding-drawer';
import { Button } from '@/shared/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/shared/components/ui/dialog';
import { TableLoadingState } from '@/shared/components/crm/table-loading-state';
import { toast } from 'sonner';

const endpoint = '/administration/closing-requirements';
type LayoutResponse = { layout: FieldLayout; fields: CrmFieldCatalogEntry[] };
type FieldDraft = Omit<ClosingFieldInput, 'appliesTo'>;
const empty = (module: CustomFieldModule, layout: FieldLayout): FieldDraft => ({ name: '', type: 'Text', module, group: layout.groups[0].label, groupId: layout.groups[0].id, visibleInForm: true, visibleInDetails: true, order: 0, required: false, active: true, options: [], description: '' });

function FieldForm({ field, module, initialLayout, onSaved, onClose }: { field?: ClosingField; module: CustomFieldModule; initialLayout: FieldLayout; onSaved: () => void; onClose: () => void }) {
  const canDisable = useHasPermission('custom_fields.disable');
  const [layout, setLayout] = useState(initialLayout);
  const [form, setForm] = useState<FieldDraft>(() => field ? { name: field.name, type: field.type, module: field.module, group: field.group, groupId: field.groupId ?? layout.groups.find(group => group.label === field.group)?.id, visibleInForm: field.visibleInForm, visibleInDetails: field.visibleInDetails, order: field.order, required: field.required, active: field.active, options: [...field.options], description: field.description } : empty(module, layout));
  const [error, setError] = useState(''), [busy, setBusy] = useState(false), [addingGroup, setAddingGroup] = useState(false), [groupName, setGroupName] = useState('');
  const update = <K extends keyof FieldDraft>(key: K, value: FieldDraft[K]) => setForm(previous => ({ ...previous, [key]: value }));
  const addGroup = async () => {
    if (busy || !groupName.trim()) return; setBusy(true); setError('');
    try { const result = (await apiClient.patch<{ data: LayoutResponse }>(`${endpoint}/layout/${module}`, { action: 'add', label: groupName })).data; const added = result.layout.groups.find(group => !layout.groups.some(previous => previous.id === group.id))!; setLayout(result.layout); setForm(previous => ({ ...previous, groupId: added.id, group: added.label })); setAddingGroup(false); setGroupName(''); }
    catch (failure) { setError(failure instanceof Error ? failure.message : 'Unable to add group.'); } finally { setBusy(false); }
  };
  return <form className="flex h-full min-h-0 flex-col" noValidate onSubmit={async event => {
    event.preventDefault(); if (busy) return; const parsed = ClosingFieldInputSchema.safeParse(form);
    if (!parsed.success) { setError(parsed.error.issues.map(issue => issue.message).join(' ')); return; } setBusy(true); setError('');
    try { if (field) await apiClient.patch(`${endpoint}/${field.id}`, parsed.data); else await apiClient.post(endpoint, parsed.data); toast.success(field ? 'Field updated' : 'Field created'); onSaved(); }
    catch (failure) { setError(failure instanceof Error ? failure.message : 'Unable to save field.'); } finally { setBusy(false); }
  }}>
    <div className={panelBodyClass + ' space-y-5'}>
      <label className="block space-y-1 text-sm">Display label<input autoFocus required maxLength={100} className={panelInputClass} value={form.name} onChange={event => update('name', event.target.value)} /></label>
      <label className="block space-y-1 text-sm">Type<select disabled={!!field} className={panelInputClass} value={form.type} onChange={event => update('type', event.target.value as FieldDraft['type'])}>{CLOSING_FIELD_TYPES.map(type => <option key={type}>{type}</option>)}</select></label>
      <p className="text-xs text-muted-foreground">Module: {CUSTOM_FIELD_MODULE_LABELS[module]}{field ? ` · Technical key: customFieldValues.${field.id}` : ''}. Type, module and technical key stay fixed after creation.</p>
      <div className="space-y-2"><label className="block space-y-1 text-sm">Group<select required className={panelInputClass} value={form.groupId ?? ''} disabled={!!field && isClosedWonField(field)} onChange={event => { const group = layout.groups.find(group => group.id === event.target.value)!; setForm(previous => ({ ...previous, groupId: group.id, group: group.label })); }}>{layout.groups.filter(group => !field || (group.id === CLOSED_WON_GROUP_ID) === isClosedWonField(field)).map(group => <option key={group.id} value={group.id}>{group.label}</option>)}</select></label><Button type="button" variant="outline" onClick={() => setAddingGroup(true)}>Add Group</Button>
      {addingGroup && <div className="flex flex-wrap gap-2"><input aria-label="New field group name" maxLength={100} value={groupName} className={panelInputClass} onChange={event => setGroupName(event.target.value)} /><Button type="button" disabled={busy || !groupName.trim()} onClick={() => void addGroup()}>Add and select</Button><Button type="button" variant="ghost" onClick={() => setAddingGroup(false)}>Cancel</Button></div>}</div>
      <label className="flex min-h-10 items-center justify-between gap-3">Required<input type="checkbox" checked={form.required} onChange={event => update('required', event.target.checked)} /></label>
      <label className="flex min-h-10 items-center justify-between gap-3">Show in Forms<input type="checkbox" checked={form.visibleInForm} onChange={event => update('visibleInForm', event.target.checked)} /></label>
      <label className="flex min-h-10 items-center justify-between gap-3">Show in Details<input type="checkbox" checked={form.visibleInDetails} onChange={event => update('visibleInDetails', event.target.checked)} /></label>
      {isClosedWonField(form) && <p className="text-xs text-muted-foreground">Required closing evidence stays enforced in the closing dialog regardless of Details visibility.</p>}
      {field && <label className="flex min-h-10 items-center justify-between gap-3">Enabled<input type="checkbox" disabled={!canDisable} checked={form.active} onChange={event => update('active', event.target.checked)} /></label>}
      <label className="block space-y-1 text-sm">Description<textarea maxLength={1000} className={panelInputClass} rows={3} value={form.description} onChange={event => update('description', event.target.value)} /></label>
      {form.type === 'Dropdown' && <label className="block space-y-1 text-sm">Options, one per line<textarea className={panelInputClass} rows={5} value={form.options.join('\n')} onChange={event => update('options', event.target.value.split('\n'))} /></label>}
      {error && <p role="alert" className="text-sm text-destructive">{error}</p>}
    </div><div className={panelFooterClass + ' justify-end'}><Button type="button" variant="outline" disabled={busy} onClick={onClose}>Cancel</Button><Button disabled={busy}>{busy ? 'Saving…' : 'Save field'}</Button></div>
  </form>;
}

function NativeFieldForm({ field, layout, onSaved, onClose }: { field: CrmFieldCatalogEntry; layout: FieldLayout; onSaved: () => void; onClose: () => void }) {
  const [label, setLabel] = useState(field.label), [groupId, setGroupId] = useState(field.groupId), [visibleInForm, setVisibleInForm] = useState(field.visibleInForm), [visibleInDetails, setVisibleInDetails] = useState(field.visibleInDetails), [busy, setBusy] = useState(false), [error, setError] = useState('');
  return <form className="space-y-5 p-5" onSubmit={async event => { event.preventDefault(); if (busy) return; setBusy(true); setError(''); try { await apiClient.patch(`${endpoint}/layout/${field.module}`, { action: 'field', technicalKey: field.technicalKey, label, groupId, visibleInForm, visibleInDetails }); onSaved(); } catch (failure) { setError(failure instanceof Error ? failure.message : 'Unable to save field.'); } finally { setBusy(false); } }}>
    <label className="block space-y-1 text-sm">Display label<input required maxLength={100} className={panelInputClass} value={label} onChange={event => setLabel(event.target.value)} /></label><p className="text-xs text-muted-foreground">System · {field.type} · {field.technicalKey}</p>
    <label className="block space-y-1 text-sm">Group<select className={panelInputClass} value={groupId} onChange={event => setGroupId(event.target.value)}>{layout.groups.filter(group => group.id !== CLOSED_WON_GROUP_ID).map(group => <option key={group.id} value={group.id}>{group.label}</option>)}</select></label>
    <label className="flex min-h-10 items-center justify-between">Show in Forms<input type="checkbox" disabled={field.mandatory} checked={visibleInForm} onChange={event => setVisibleInForm(event.target.checked)} /></label><label className="flex min-h-10 items-center justify-between">Show in Details<input type="checkbox" checked={visibleInDetails} onChange={event => setVisibleInDetails(event.target.checked)} /></label>
    {field.mandatory && <p className="text-xs text-muted-foreground">This required system input stays available in forms.</p>}{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" disabled={busy} onClick={onClose}>Cancel</Button><Button disabled={busy}>{busy ? 'Saving…' : 'Save field'}</Button></div>
  </form>;
}

export function ClosingFieldsSettings() {
  const canEdit = useHasPermission('custom_fields.edit'), canCreate = useHasPermission('custom_fields.create'), canDelete = useHasPermission('custom_fields.delete');
  const [module, setModule] = useState<CustomFieldModule>('leads'), [search, setSearch] = useState(''), [panel, setPanel] = useState<'new' | CrmFieldCatalogEntry | null>(null), [manageGroups, setManageGroups] = useState(false), [groupName, setGroupName] = useState(''), [groupLabels, setGroupLabels] = useState<Record<string, string>>({}), [moveTargets, setMoveTargets] = useState<Record<string, string>>({}), [pending, setPending] = useState(false);
  const query = useCachedPage<{ definitions: ClosingField[]; layout: FieldLayout }>({ module: 'settings', params: { fieldLayout: module }, revalidateOnInvalidation: true, fetchFn: async signal => { const [fields, layout] = await Promise.all([apiClient.get<{ data: ClosingField[] }>(endpoint, { signal }), apiClient.get<{ data: LayoutResponse }>(`${endpoint}/layout/${module}`, { signal })]); return { definitions: fields.data.map(normalizeCustomField), layout: layout.data.layout }; } });
  const layout = query.data?.layout ?? defaultFieldLayout(module), fields = getCrmFieldCatalog(module, query.data?.definitions ?? [], layout), filtered = fields.filter(field => `${field.label} ${field.technicalKey} ${field.group}`.toLowerCase().includes(search.trim().toLowerCase()));
  const mutateLayout = async (input: unknown) => { if (pending) return; setPending(true); try { await apiClient.patch(`${endpoint}/layout/${module}`, input); await query.refetch(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to update layout'); } finally { setPending(false); } };
  return <div className="min-w-0 space-y-5">
    <PageHeader title="Customize Fields" subtitle="Manage module labels, sections and field presentation." actions={<div className="flex flex-wrap gap-2">{canEdit && <Button variant="outline" onClick={() => setManageGroups(true)}>Manage Field Groups</Button>}{canCreate && <Button onClick={() => setPanel('new')}><Plus size={14} />Add Field</Button>}</div>} />
    <div className="flex flex-wrap gap-3"><select aria-label="Module" className={panelInputClass + ' sm:max-w-48'} value={module} onChange={event => { setModule(event.target.value as CustomFieldModule); setPanel(null); }}>{CUSTOM_FIELD_MODULES.map(module => <option key={module} value={module}>{CUSTOM_FIELD_MODULE_LABELS[module]}</option>)}</select><input aria-label="Search fields" placeholder="Search labels, technical keys or groups…" className={panelInputClass + ' sm:max-w-md'} value={search} onChange={event => setSearch(event.target.value)} /></div>
    {query.isInitialLoad ? <TableLoadingState label="Loading fields" /> : query.error ? <p role="alert">{query.error}<Button onClick={() => void query.refetch()}>Retry</Button></p> : <div className="overflow-x-auto rounded-lg border border-border"><table className="w-full min-w-[1050px] text-left text-xs"><thead className="bg-muted"><tr>{['Label', 'System/Custom', 'Type', 'Technical variable key', 'Group', 'Required', 'Show in Forms', 'Show in Details', 'Actions'].map(label => <th key={label} className="p-3 font-semibold">{label}</th>)}</tr></thead><tbody>{filtered.map(field => <tr key={field.technicalKey} className="border-t border-border"><td className="p-3 font-medium">{field.label}{!field.active && <span className="block text-muted-foreground">Disabled</span>}</td><td className="p-3">{field.kind}</td><td className="p-3">{field.type}</td><td className="max-w-64 break-all p-3 font-mono">{field.technicalKey}</td><td className="p-3">{field.group}</td><td className="p-3">{field.required ? 'Yes' : 'No'}</td>{(['visibleInForm', 'visibleInDetails'] as const).map(key => <td key={key} className="p-3"><input aria-label={`${key === 'visibleInForm' ? 'Show in Forms' : 'Show in Details'}: ${field.label}`} type="checkbox" checked={field[key]} disabled={!canEdit || pending || (key === 'visibleInForm' && field.mandatory)} onChange={event => void mutateLayout({ action: 'field', technicalKey: field.technicalKey, [key]: event.target.checked })} /></td>)}<td className="p-2"><div className="flex gap-1">{canEdit && <><Button variant="ghost" size="sm" onClick={() => setPanel(field)}>Edit</Button>{(['up', 'down'] as const).map(direction => <Button key={direction} variant="ghost" size="icon" aria-label={`Move ${field.label} ${direction}`} disabled={pending} onClick={() => void mutateLayout({ action: 'field', technicalKey: field.technicalKey, direction })}>{direction === 'up' ? <ArrowUp size={14} /> : <ArrowDown size={14} />}</Button>)}</>}{canDelete && field.kind === 'Custom' && <Button variant="ghost" size="sm" className="text-destructive" disabled={pending} onClick={async () => { if (!window.confirm(`Delete “${field.label}” from current configuration? Historical values and evidence will be retained.`)) return; setPending(true); try { await apiClient.delete(`${endpoint}/${field.customFieldId}`); await query.refetch(); toast.success('Field deleted'); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to delete field'); } finally { setPending(false); } }}>Delete</Button>}</div></td></tr>)}</tbody></table>{!filtered.length && <p className="p-5 text-sm text-muted-foreground">No fields match your search.</p>}</div>}
    <SlidingDrawer isOpen={panel !== null} onClose={() => setPanel(null)} title={panel === 'new' ? 'Add Field' : 'Edit Field'}>{panel && (panel === 'new' || panel.customFieldId ? <FieldForm key={panel === 'new' ? module : panel.technicalKey} field={panel === 'new' ? undefined : query.data?.definitions.find(field => field.id === panel.customFieldId)} module={module} initialLayout={layout} onClose={() => setPanel(null)} onSaved={() => { setPanel(null); void query.refetch(); }} /> : <NativeFieldForm field={panel} layout={layout} onClose={() => setPanel(null)} onSaved={() => { setPanel(null); void query.refetch(); }} />)}</SlidingDrawer>
    <Dialog open={manageGroups} onOpenChange={setManageGroups}><DialogContent className="max-h-[85dvh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>{CUSTOM_FIELD_MODULE_LABELS[module]} Field Groups</DialogTitle></DialogHeader><div className="flex gap-2"><input aria-label="New group name" placeholder="New group name" maxLength={100} className={panelInputClass} value={groupName} onChange={event => setGroupName(event.target.value)} /><Button disabled={pending || !groupName.trim()} onClick={async () => { await mutateLayout({ action: 'add', label: groupName }); setGroupName(''); }}>Add</Button></div><div className="space-y-3">{[...layout.groups].sort((a, b) => a.order - b.order).map(group => <div key={group.id} className="space-y-2 rounded-lg border p-3"><div className="flex flex-wrap items-center gap-2"><input aria-label={`Group label: ${group.label}`} className={panelInputClass + ' flex-1'} maxLength={100} value={groupLabels[group.id] ?? group.label} onChange={event => setGroupLabels(previous => ({ ...previous, [group.id]: event.target.value }))} /><Button variant="outline" disabled={pending} onClick={() => void mutateLayout({ action: 'rename', groupId: group.id, label: groupLabels[group.id] ?? group.label })}>Rename</Button>{(['up', 'down'] as const).map(direction => <Button key={direction} variant="ghost" size="icon" aria-label={`Move ${group.label} ${direction}`} disabled={pending} onClick={() => void mutateLayout({ action: 'moveGroup', groupId: group.id, direction })}>{direction === 'up' ? <ArrowUp size={14} /> : <ArrowDown size={14} />}</Button>)}</div><p className="text-xs text-muted-foreground">{fields.filter(field => field.groupId === group.id).length} fields{group.protected ? ' · Protected closing evidence context' : ''}</p>{!group.protected && <div className="flex flex-wrap gap-2"><select aria-label={`Move fields from ${group.label} to`} className={panelInputClass + ' flex-1'} value={moveTargets[group.id] ?? ''} onChange={event => setMoveTargets(previous => ({ ...previous, [group.id]: event.target.value }))}><option value="">Move fields to…</option>{layout.groups.filter(target => target.id !== group.id && !target.protected).map(target => <option key={target.id} value={target.id}>{target.label}</option>)}</select><Button variant="outline" disabled={pending} onClick={() => void mutateLayout({ action: 'delete', groupId: group.id, ...(moveTargets[group.id] ? { moveToGroupId: moveTargets[group.id] } : {}) })}>Delete Group</Button></div>}</div>)}</div></DialogContent></Dialog>
  </div>;
}
