import type { Contact } from '../types';

// ─── Contacts (Leads) ─────────────────────────────────────────────────────────

export const MOCK_LEADS: Contact[] = [
  {
    id: 'lead_1',
    tenantId: 'tenant_demo',
    firstName: 'John',
    lastName: 'Doe',
    customerType: 'Organization',
    companyName: 'TechFlow Solutions',
    contactPerson: 'John Doe',
    jobTitle: 'CEO',
    email: 'john@techflow.com',
    phone: '(555) 010-1234',
    serviceRequired: 'CCTV Surveillance System',
    leadSource: 'Referral',
    estimatedValue: 85000,
    assignedUserId: 'user_sales_1',
    expectedCloseDate: '2026-05-15',
    notes: 'Looking to install 50 IP cameras across their new facility. High priority.',
    status: 'Hot',
    score: 95,
    createdAt: '2026-03-10T10:00:00.000Z',
    organizationId: 'org_1',
    productInterest: 'CCTV Surveillance System',
    streetAddress: '100 Tech Park Drive',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_2',
    tenantId: 'tenant_demo',
    firstName: 'Jane',
    lastName: 'Smith',
    customerType: 'Organization',
    companyName: 'Globex Corporation',
    contactPerson: 'Jane Smith',
    jobTitle: 'CTO',
    email: 'jane@globex.com',
    phone: '(555) 010-2345',
    serviceRequired: 'Structured Cabling',
    leadSource: 'LinkedIn',
    estimatedValue: 45000,
    assignedUserId: 'user_sales_2',
    expectedCloseDate: '2026-06-01',
    notes: 'Needs complete structured cabling for data and voice before Q3 move-in.',
    status: 'Warm',
    score: 75,
    createdAt: '2026-03-15T14:30:00.000Z',
    organizationId: 'org_2',
    productInterest: 'Structured Cabling',
    streetAddress: '200 Innovation Ave',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_3',
    tenantId: 'tenant_demo',
    firstName: 'Tony',
    lastName: 'Stark',
    customerType: 'Organization',
    companyName: 'Stark Industries',
    contactPerson: 'Tony Stark',
    jobTitle: 'Director of Engineering',
    email: 't.stark@starkind.com',
    phone: '(555) 010-3456',
    serviceRequired: 'Biometrics & Door Access',
    leadSource: 'Website',
    estimatedValue: 120000,
    assignedUserId: 'user_sales_3',
    expectedCloseDate: '2026-04-20',
    notes: 'Interested in smart locks and biometric access for their R&D labs.',
    status: 'Hot',
    score: 92,
    createdAt: '2026-03-20T09:15:00.000Z',
    organizationId: 'org_3',
    productInterest: 'Biometrics & Door Access',
    streetAddress: '300 Stark Tower',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_4',
    tenantId: 'tenant_demo',
    firstName: 'Bill',
    lastName: 'Lumbergh',
    customerType: 'Organization',
    companyName: 'Initech',
    contactPerson: 'Bill Lumbergh',
    jobTitle: 'VP Operations',
    email: 'bill@initech.com',
    phone: '(555) 010-4567',
    serviceRequired: 'Fire Detection and Alarm System',
    leadSource: 'Cold Call',
    estimatedValue: 15000,
    assignedUserId: 'user_sales_1',
    expectedCloseDate: '2026-07-10',
    notes: 'Just gathering information for next year budget. Needs FDAS compliance.',
    status: 'Cold',
    score: 35,
    createdAt: '2026-02-25T11:00:00.000Z',
    organizationId: 'org_4',
    productInterest: 'Fire Detection and Alarm System',
    streetAddress: '400 LexCorp Way',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_5',
    tenantId: 'tenant_demo',
    firstName: 'Albert',
    lastName: 'Wesker',
    customerType: 'Organization',
    companyName: 'Umbrella Corp',
    contactPerson: 'Albert Wesker',
    jobTitle: 'Head of Research',
    email: 'awesker@umbrella.com',
    phone: '(555) 010-5678',
    serviceRequired: 'Servers & Data Cabinets',
    leadSource: 'Conference',
    estimatedValue: 250000,
    assignedUserId: 'user_sales_2',
    expectedCloseDate: '2026-05-30',
    notes: 'Huge potential, looking for enterprise-grade servers and data cabinets.',
    status: 'Warm',
    score: 68,
    createdAt: '2026-03-05T16:45:00.000Z',
    organizationId: 'org_5',
    productInterest: 'Servers & Data Cabinets',
    streetAddress: '500 Aperture Lab',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_6',
    tenantId: 'tenant_demo',
    firstName: 'William',
    lastName: 'Bell',
    customerType: 'Organization',
    companyName: 'Massive Dynamic',
    contactPerson: 'William Bell',
    jobTitle: 'Founder',
    email: 'w.bell@massive.com',
    phone: '(555) 010-6789',
    serviceRequired: 'IP PBX & IP Phones',
    leadSource: 'Referral',
    estimatedValue: 75000,
    assignedUserId: 'user_sales_3',
    expectedCloseDate: '2026-04-15',
    notes: 'Ready to sign for new IP PBX system, just waiting on legal review.',
    status: 'Closed',
    score: 100,
    createdAt: '2026-01-10T10:20:00.000Z',
    organizationId: 'org_6',
    productInterest: 'IP PBX & IP Phones',
    streetAddress: '600 Cyberdine Sys',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_7',
    tenantId: 'tenant_demo',
    firstName: 'Robert',
    lastName: 'Thorn',
    customerType: 'Individual',
    companyName: '',
    contactPerson: 'Robert Thorn',
    jobTitle: 'Homeowner',
    email: 'r.thorn@private-life.com',
    phone: '(555) 010-7890',
    serviceRequired: 'Electric Fence & Perimeter Security',
    leadSource: 'Email Campaign',
    estimatedValue: 30000,
    assignedUserId: 'user_sales_1',
    expectedCloseDate: '2026-08-01',
    notes: 'Residential contact. Wants top-tier physical security and a secure electric fence around his primary estate.',
    status: 'Cancelled',
    score: 0,
    createdAt: '2026-02-01T13:10:00.000Z',
    streetAddress: '782 Woodlands Way, Sector 10',
    productInterest: 'Electric Fence & Perimeter Security',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_8',
    tenantId: 'tenant_demo',
    firstName: 'Miles',
    lastName: 'Dyson',
    customerType: 'Organization',
    companyName: 'Cyberdyne Systems',
    contactPerson: 'Miles Dyson',
    jobTitle: 'Director of Special Projects',
    email: 'm.dyson@cyberdyne.com',
    phone: '(555) 010-8901',
    serviceRequired: 'CCTV Surveillance System',
    leadSource: 'Referral',
    estimatedValue: 150000,
    assignedUserId: 'user_sales_1',
    expectedCloseDate: '2026-06-20',
    notes: 'Urgent requirement for high-security surveillance in the lab area.',
    status: 'Hot',
    score: 98,
    createdAt: '2026-04-01T10:00:00.000Z',
    organizationId: 'org_8',
    productInterest: 'CCTV Surveillance System',
    streetAddress: '800 Bugle St',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_9',
    tenantId: 'tenant_demo',
    firstName: 'Lucius',
    lastName: 'Fox',
    customerType: 'Organization',
    companyName: 'Wayne Enterprises',
    contactPerson: 'Lucius Fox',
    jobTitle: 'CEO',
    email: 'l.fox@wayneent.com',
    phone: '(555) 010-9012',
    serviceRequired: 'Structured Cabling',
    leadSource: 'Website',
    estimatedValue: 65000,
    assignedUserId: 'user_sales_2',
    expectedCloseDate: '2026-07-15',
    notes: 'Planning a major office expansion, needs full networking infrastructure.',
    status: 'Warm',
    score: 72,
    createdAt: '2026-04-02T14:30:00.000Z',
    organizationId: 'org_9',
    productInterest: 'Structured Cabling',
    streetAddress: '900 Planet Blvd',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_10',
    tenantId: 'tenant_demo',
    firstName: 'Norman',
    lastName: 'Osborn',
    customerType: 'Organization',
    companyName: 'Oscorp Industries',
    contactPerson: 'Norman Osborn',
    jobTitle: 'Chairman',
    email: 'n.osborn@oscorp.com',
    phone: '(555) 010-0123',
    serviceRequired: 'IP PBX & IP Phones',
    leadSource: 'Cold Call',
    estimatedValue: 25000,
    assignedUserId: 'user_sales_3',
    expectedCloseDate: '2026-09-01',
    notes: 'Initial inquiry about upgrading their legacy phone system.',
    status: 'Cold',
    score: 28,
    createdAt: '2026-04-03T09:15:00.000Z',
    organizationId: 'org_10',
    productInterest: 'IP PBX & IP Phones',
    streetAddress: '1000 Amazon St',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_11',
    tenantId: 'tenant_demo',
    firstName: 'Lex',
    lastName: 'Luthor',
    customerType: 'Organization',
    companyName: 'LexCorp',
    contactPerson: 'Lex Luthor',
    jobTitle: 'CEO',
    email: 'lex@lexcorp.com',
    phone: '(555) 010-1234',
    serviceRequired: 'Biometrics & Door Access',
    leadSource: 'LinkedIn',
    estimatedValue: 180000,
    assignedUserId: 'user_sales_2',
    expectedCloseDate: '2026-05-30',
    notes: 'Requires state-of-the-art biometric security for their main tower.',
    status: 'Hot',
    score: 94,
    createdAt: '2026-04-04T11:00:00.000Z',
    organizationId: 'org_11',
    productInterest: 'Biometrics & Door Access',
    streetAddress: '1100 Silicon Blvd',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_12',
    tenantId: 'tenant_demo',
    firstName: 'Cave',
    lastName: 'Johnson',
    customerType: 'Organization',
    companyName: 'Aperture Science',
    contactPerson: 'Cave Johnson',
    jobTitle: 'Founder',
    email: 'cave@aperture.com',
    phone: '(555) 010-2345',
    serviceRequired: 'Servers & Data Cabinets',
    leadSource: 'Conference',
    estimatedValue: 300000,
    assignedUserId: 'user_sales_1',
    expectedCloseDate: '2026-08-15',
    notes: 'Looking for robust server solutions for their testing facilities.',
    status: 'Warm',
    score: 65,
    createdAt: '2026-04-05T16:45:00.000Z',
    organizationId: 'org_12',
    productInterest: 'Servers & Data Cabinets',
    streetAddress: '1200 Enterprise Rd',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_13',
    tenantId: 'tenant_demo',
    firstName: 'Sarah',
    lastName: 'Connor',
    customerType: 'Individual',
    companyName: '',
    contactPerson: 'Sarah Connor',
    jobTitle: 'Private Resident',
    email: 'sconnor@cyber-survive.org',
    phone: '(555) 010-9944',
    serviceRequired: 'High-Definition CCTV Coverage',
    leadSource: 'Referral',
    estimatedValue: 18000,
    assignedUserId: 'user_sales_3',
    expectedCloseDate: '2026-05-02',
    notes: 'Extremely focused on zero blind-spots around her residence. Requires night-vision cams.',
    status: 'Hot',
    score: 95,
    createdAt: '2026-04-06T08:30:00.000Z',
    streetAddress: '404 Hidden Valley Road',
    productInterest: 'High-Definition CCTV Coverage',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_14',
    tenantId: 'tenant_demo',
    firstName: 'Bruce',
    lastName: 'Wayne',
    customerType: 'Individual',
    companyName: '',
    contactPerson: 'Bruce Wayne',
    jobTitle: 'Private Resident',
    email: 'bwayne@wayne-estate.com',
    phone: '(555) 010-9000',
    serviceRequired: 'Intrusion Detection System',
    leadSource: 'Referral',
    estimatedValue: 89000,
    assignedUserId: 'user_sales_2',
    expectedCloseDate: '2026-06-10',
    notes: 'Wants specialized subterranean motion detectors and thermal cameras installed around private property lines.',
    status: 'Hot',
    score: 99,
    createdAt: '2026-04-07T14:00:00.000Z',
    streetAddress: '1007 Mountain Crest Blvd',
    productInterest: 'Intrusion Detection System',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_15',
    tenantId: 'tenant_demo',
    firstName: 'Peter',
    lastName: 'Parker',
    customerType: 'Individual',
    companyName: '',
    contactPerson: 'Peter Parker',
    jobTitle: 'Freelance Photographer',
    email: 'pparker@dailybugle.net',
    phone: '(555) 012-3498',
    serviceRequired: 'Basic Home Assessment',
    leadSource: 'Web Form',
    estimatedValue: 1200,
    assignedUserId: 'user_sales_3',
    expectedCloseDate: '2026-05-15',
    notes: 'Needs simple door access logs and smart lock for apartment.',
    status: 'Warm',
    score: 60,
    createdAt: '2026-04-08T10:00:00.000Z',
    streetAddress: '20 Ingram St, Queens',
    productInterest: 'Basic Home Assessment',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_16',
    tenantId: 'tenant_demo',
    firstName: 'Clark',
    lastName: 'Kent',
    customerType: 'Organization',
    companyName: 'Daily Planet',
    contactPerson: 'Clark Kent',
    jobTitle: 'Investigative Journalist',
    email: 'ckent@dailyplanet.com',
    phone: '(555) 013-4455',
    serviceRequired: 'High-speed Network Routing',
    leadSource: 'Referral',
    estimatedValue: 55000,
    assignedUserId: 'user_sales_1',
    expectedCloseDate: '2026-06-01',
    notes: 'Upgrading the printing press and editorial floor network.',
    status: 'Hot',
    score: 85,
    createdAt: '2026-04-09T09:15:00.000Z',
    organizationId: 'org_16',
    productInterest: 'High-speed Network Routing',
    streetAddress: '1600 Business Ctr',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_17',
    tenantId: 'tenant_demo',
    firstName: 'Diana',
    lastName: 'Prince',
    customerType: 'Organization',
    companyName: 'Themyscira Antiquities',
    contactPerson: 'Diana Prince',
    jobTitle: 'Curator',
    email: 'dprince@antiquities.org',
    phone: '(555) 018-9999',
    serviceRequired: 'Museum Security System',
    leadSource: 'Social Media Advertisement',
    estimatedValue: 210000,
    assignedUserId: 'user_sales_2',
    expectedCloseDate: '2026-07-20',
    notes: 'Requires artifact-level vibration sensors, glass-break detectors, and round-the-clock monitoring integration.',
    status: 'Hot',
    score: 97,
    createdAt: '2026-04-10T11:45:00.000Z',
    organizationId: 'org_17',
    productInterest: 'Museum Security System',
    streetAddress: '1700 Industrial Ave',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_18',
    tenantId: 'tenant_demo',
    firstName: 'Barry',
    lastName: 'Allen',
    customerType: 'Organization',
    companyName: 'Central City PD',
    contactPerson: 'Barry Allen',
    jobTitle: 'CSI Forensics',
    email: 'ballen@ccpd.gov',
    phone: '(555) 019-8877',
    serviceRequired: 'Lab Data Cabinets',
    leadSource: 'Cold Call',
    estimatedValue: 40000,
    assignedUserId: 'user_sales_3',
    expectedCloseDate: '2026-05-30',
    notes: 'Expanding the forensic labs, needs isolated subnet and secured data cabinets.',
    status: 'Cold',
    score: 45,
    createdAt: '2026-04-11T16:00:00.000Z',
    organizationId: 'org_18',
    productInterest: 'Lab Data Cabinets',
    streetAddress: '1800 Harbor Blvd',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_19',
    tenantId: 'tenant_demo',
    firstName: 'Arthur',
    lastName: 'Curry',
    customerType: 'Organization',
    companyName: 'Amnesty Bay Lighthouse',
    contactPerson: 'Arthur Curry',
    jobTitle: 'Lighthouse Keeper',
    email: 'acurry@amnestybay.com',
    phone: '(555) 011-2233',
    serviceRequired: 'Waterproof Cabling & Radio',
    leadSource: 'Web Form',
    estimatedValue: 15000,
    assignedUserId: 'user_sales_1',
    expectedCloseDate: '2026-05-20',
    notes: 'Needs weather-sealed network cabling to the mainland.',
    status: 'Warm',
    score: 65,
    createdAt: '2026-04-12T13:30:00.000Z',
    organizationId: 'org_19',
    productInterest: 'Waterproof Cabling & Radio',
    streetAddress: '1900 Market St',
    city: 'Metropolis',
    province: 'NY',
  },
  {
    id: 'lead_20',
    tenantId: 'tenant_demo',
    firstName: 'Victor',
    lastName: 'Stone',
    customerType: 'Individual',
    companyName: '',
    contactPerson: 'Victor Stone',
    jobTitle: 'Student Athlete',
    email: 'vstone@gcu.edu',
    phone: '(555) 019-1122',
    serviceRequired: 'Smart Home Hub',
    leadSource: 'Referral',
    estimatedValue: 5000,
    assignedUserId: 'user_sales_2',
    expectedCloseDate: '2026-04-30',
    notes: 'Wants an integrated smart home setup with complete automation control from device.',
    status: 'Closed',
    score: 100,
    createdAt: '2026-04-13T09:00:00.000Z',
    streetAddress: '150 Grid Campus',
    productInterest: 'Smart Home Hub',
    city: 'Metropolis',
    province: 'NY',
  },
];
