import type { Pipeline, Deal } from '../types';

// ─── Pipelines ────────────────────────────────────────────────────────────────

export const MOCK_PIPELINES: Pipeline[] = [
  {
    id: 'pipe_sales',
    tenantId: 'tenant_demo',
    name: 'Sales Inquiries',
    stages: [
      { id: 'stage_lead',        name: 'Discovery',    order: 0 },
      { id: 'stage_assessment',  name: 'Assessment',   order: 1 },
      { id: 'stage_proposal',    name: 'Proposal',     order: 2 },
      { id: 'stage_negotiation', name: 'Negotiation',  order: 3 },
      { id: 'stage_won',         name: 'Closed Won',   order: 4 },
      { id: 'stage_lost',        name: 'Closed Lost',  order: 5 },
    ],
  },
  {
    id: 'pipe_tech',
    tenantId: 'tenant_demo',
    name: 'Technical Support',
    stages: [
      { id: 'stage_ticket',   name: 'Ticket Opened', order: 0 },
      { id: 'stage_review',   name: 'Under Review',  order: 1 },
      { id: 'stage_progress', name: 'In Progress',   order: 2 },
      { id: 'stage_resolved', name: 'Resolved',      order: 3 },
    ],
  },
  {
    id: 'pipe_project',
    tenantId: 'tenant_demo',
    name: 'Project Implementation',
    stages: [
      { id: 'stage_init',    name: 'Initiation', order: 0 },
      { id: 'stage_plan',    name: 'Planning',   order: 1 },
      { id: 'stage_exec',    name: 'Execution',  order: 2 },
      { id: 'stage_handoff', name: 'Handoff',    order: 3 },
    ],
  },
  {
    id: 'pipe_aftersales',
    tenantId: 'tenant_demo',
    name: 'After-sales Concerns',
    stages: [
      { id: 'stage_inquiry',    name: 'Inquiry',    order: 0 },
      { id: 'stage_followup',   name: 'Follow-up',  order: 1 },
      { id: 'stage_conclusion', name: 'Conclusion', order: 2 },
    ],
  },
];

// ─── Deals ────────────────────────────────────────────────────────────────────

export const MOCK_DEALS: Deal[] = [
  {
    id: 'deal_1',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_proposal',
    title: 'Office Building CCTV System',
    companyName: 'Innovate Solutions',
    contactPerson: 'Sarah Johnson',
    value: 85000,
    priority: 'High',
    expectedCloseDate: '2026-05-15',
    description: '50-camera surveillance system for corporate headquarters',
    assignedUserId: 'user_sales_2',
    order: 0,
    createdAt: '2026-03-12T10:00:00.000Z',
    history: [
      { stageId: 'stage_lead',       timestamp: '2026-03-12T10:00:00.000Z', userId: 'user_sales_2', note: 'Deal created' },
      { stageId: 'stage_assessment', timestamp: '2026-03-14T11:30:00.000Z', userId: 'user_sales_2', note: 'Completed site inspection' },
      { stageId: 'stage_proposal',   timestamp: '2026-03-18T09:00:00.000Z', userId: 'user_sales_2', note: 'Proposal sent to customer' },
    ],
  },
  {
    id: 'deal_2',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_negotiation',
    title: 'Biometric Access Control',
    companyName: 'Nexus Digital',
    contactPerson: 'Robert Taylor',
    value: 68000,
    priority: 'Medium',
    expectedCloseDate: '2026-04-25',
    description: 'Fingerprint and card-based access for 50 doors',
    assignedUserId: 'user_sales_1',
    order: 1,
    createdAt: '2026-03-18T14:30:00.000Z',
    history: [
      { stageId: 'stage_lead',        timestamp: '2026-03-18T14:30:00.000Z', userId: 'user_sales_1', note: 'Deal created' },
      { stageId: 'stage_assessment',  timestamp: '2026-03-20T10:00:00.000Z', userId: 'user_sales_1' },
      { stageId: 'stage_proposal',    timestamp: '2026-03-22T15:45:00.000Z', userId: 'user_sales_1' },
      { stageId: 'stage_negotiation', timestamp: '2026-03-25T10:00:00.000Z', userId: 'user_sales_1' },
    ],
  },
  {
    id: 'deal_3',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_project',
    stageId: 'stage_proposal',
    title: 'Enterprise WiFi Infrastructure',
    companyName: 'TechCorp Inc',
    contactPerson: 'John Smith',
    value: 125000,
    priority: 'High',
    expectedCloseDate: '2026-04-30',
    description: 'Complete WiFi 6E deployment for 10-floor office building',
    assignedUserId: 'user_sales_3',
    order: 0,
    createdAt: '2026-03-22T09:15:00.000Z',
    history: [
      { stageId: 'stage_lead',      timestamp: '2026-03-22T09:15:00.000Z', userId: 'user_sales_3', note: 'Deal created' },
      { stageId: 'stage_assessment', timestamp: '2026-03-24T14:00:00.000Z', userId: 'user_sales_3' },
      { stageId: 'stage_proposal',   timestamp: '2026-03-26T11:00:00.000Z', userId: 'user_sales_3' },
    ],
  },
  {
    id: 'deal_lost_1',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_lost',
    title: 'Server & Data Cabinet Upgrade',
    companyName: 'OldTech Solutions',
    contactPerson: 'Arthur Dent',
    value: 15000,
    priority: 'Low',
    expectedCloseDate: '2026-03-20',
    description: 'Upgrade of legacy servers and data cabinets.',
    assignedUserId: 'user_sales_1',
    lostReason: 'Budget was cut due to internal restructuring.',
    order: 0,
    createdAt: '2026-02-15T14:00:00.000Z',
    history: [
      { stageId: 'stage_lead',     timestamp: '2026-02-15T14:00:00.000Z', userId: 'user_sales_1', note: 'Deal created' },
      { stageId: 'stage_proposal', timestamp: '2026-02-20T10:00:00.000Z', userId: 'user_sales_1' },
      { stageId: 'stage_lost',     timestamp: '2026-03-01T15:00:00.000Z', userId: 'user_sales_1', note: 'Budget was cut due to internal restructuring.' },
    ],
  },
  {
    id: 'deal_4',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_project',
    stageId: 'stage_assessment',
    title: 'IP PBX System Installation',
    companyName: 'DataWorks',
    contactPerson: 'Michael Chen',
    value: 45000,
    priority: 'Medium',
    expectedCloseDate: '2026-05-10',
    description: 'IPBX and IP Phones for new branch office',
    assignedUserId: 'user_sales_3',
    order: 0,
    createdAt: '2026-03-25T16:45:00.000Z',
    history: [
      { stageId: 'stage_lead',       timestamp: '2026-03-25T16:45:00.000Z', userId: 'user_sales_3', note: 'Contact created' },
      { stageId: 'stage_assessment', timestamp: '2026-03-26T10:00:00.000Z', userId: 'user_sales_3', note: 'Network assessment started' },
    ],
  },
  {
    id: 'deal_5',
    tenantId: 'tenant_demo',
    pipelineId: 'pipe_sales',
    stageId: 'stage_won',
    title: 'Corporate Laptop Fleet',
    companyName: 'CloudNine Systems',
    contactPerson: 'Emily Davis',
    value: 120000,
    priority: 'High',
    expectedCloseDate: '2026-03-10',
    description: 'Procurement of 100 high-performance laptops for engineering team',
    assignedUserId: 'user_sales_2',
    order: 0,
    createdAt: '2026-02-01T09:00:00.000Z',
    history: [
      { stageId: 'stage_lead',        timestamp: '2026-02-01T09:00:00.000Z', userId: 'user_sales_2' },
      { stageId: 'stage_proposal',    timestamp: '2026-02-05T11:00:00.000Z', userId: 'user_sales_2' },
      { stageId: 'stage_negotiation', timestamp: '2026-02-25T10:00:00.000Z', userId: 'user_sales_2' },
      { stageId: 'stage_won',         timestamp: '2026-03-10T15:30:00.000Z', userId: 'user_sales_2', note: 'Contract signed' },
    ],
  },
];
