import React from 'react';
import { beforeEach, afterEach, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
const api = vi.hoisted(() => ({ mfaStatus: vi.fn(), changePassword: vi.fn(), setupMfa: vi.fn(), enableMfa: vi.fn(), disableMfa: vi.fn(), regenerateMfaRecoveryCodes: vi.fn() }));
vi.mock('@/shared/services/auth.api', () => ({ authApi: api }));
vi.mock('@/store/AuthContext', () => ({ useAuth: () => ({ user: { id: 'me' }, applyAuthUser: vi.fn() }) }));
vi.mock('sonner', () => ({ toast: { success: vi.fn() } }));
import { SecuritySettings } from '../security-settings';
beforeEach(() => { vi.resetAllMocks(); api.mfaStatus.mockResolvedValue({ data: { enabled: false, passwordChangedAt: null, recoveryCodesRemaining: 0 } }); });
afterEach(cleanup);
it('opens a password dialog without sending a change request and clears fields on cancel', async () => {
  render(<SecuritySettings />);
  fireEvent.click(screen.getByRole('button', { name: 'Change Password' }));
  const dialog = await screen.findByRole('dialog');
  expect(api.changePassword).not.toHaveBeenCalled();
  fireEvent.change(within(dialog).getByLabelText('New Password *'), { target: { value: 'Camxian1!' } });
  expect(within(dialog).getByRole('progressbar').getAttribute('aria-valuenow')).toBe('5');
  fireEvent.click(within(dialog).getByText('Cancel'));
  await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull());
  fireEvent.click(screen.getByRole('button', { name: 'Change Password' }));
  expect((await screen.findByLabelText('New Password *') as HTMLInputElement).value).toBe('');
  expect(screen.queryByText('Last changed: Never')).toBeNull();
});
it('shows one field error under the input and never sends mismatched confirmation', async () => {
  render(<SecuritySettings />); fireEvent.click(screen.getByText('Change Password'));
  await screen.findByRole('dialog');
  fireEvent.change(screen.getByLabelText('Current Password *'), { target: { value: 'OldPassword1!' } });
  fireEvent.change(screen.getByLabelText('New Password *'), { target: { value: 'Camxian2026!' } });
  fireEvent.change(screen.getByLabelText('Confirm New Password *'), { target: { value: 'Mismatch1!' } });
  fireEvent.click(within(screen.getByRole('dialog')).getByText('Change Password', { selector: 'button' }));
  expect(screen.getAllByText('Passwords do not match.')).toHaveLength(1);
  expect(screen.getByLabelText('Confirm New Password *').getAttribute('aria-describedby')).toBe('confirm-error');
  expect(api.changePassword).not.toHaveBeenCalled();
});
it('does not enable on setup and displays recovery codes only after confirmed enable', async () => {
  api.setupMfa.mockResolvedValue({ data: { secret: 'TESTSECRET', qrCode: 'data:image/png;base64,AA', expiresAt: '2026-10-01' } });
  api.enableMfa.mockResolvedValue({ data: { recoveryCodes: ['1234abcd-5678ef90'] } });
  render(<SecuritySettings />);
  await waitFor(() => expect((screen.getByText('Enable Two-Factor Authentication') as HTMLButtonElement).disabled).toBe(false));
  fireEvent.click(screen.getByText('Enable Two-Factor Authentication'));
  fireEvent.change(await screen.findByLabelText('Current Password *'), { target: { value: 'Current1!' } });
  fireEvent.click(screen.getByText('Continue'));
  expect(await screen.findByText('TESTSECRET')).toBeTruthy();
  expect(api.enableMfa).not.toHaveBeenCalled();
  fireEvent.change(screen.getByLabelText('Authenticator Code *'), { target: { value: '123456' } });
  fireEvent.click(screen.getByText('Verify & Enable'));
  expect(await screen.findByText('1234abcd-5678ef90')).toBeTruthy();
  expect(screen.queryByText('TESTSECRET')).toBeNull();
  fireEvent.click(screen.getByText('I saved my recovery codes'));
  await waitFor(() => expect(screen.queryByText('1234abcd-5678ef90')).toBeNull());
});
