import React from 'react';
import { beforeEach, afterEach, expect, it, vi } from 'vitest';
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { campaignFields } from '@leadcrm/shared';
const api = vi.hoisted(() => ({ fields: vi.fn(), preview: vi.fn(), create: vi.fn() }));
vi.mock('@/store/AuthContext', () => ({ useAuth: () => ({ user: { id: 'audience-user', tenantId: 'audience-tenant', role: 'Client Admin' }, tenant: { id: 'audience-tenant' }, isLoading: false }) }));
vi.mock('@/shared/services/audiences.api', () => ({ audiencesApi: api }));
vi.mock('@/shared/components/side-sheet', () => ({ SideSheet: ({ children }: { children: React.ReactNode }) => <div>{children}</div> }));
vi.mock('@/shared/components/crm/product-interest-select', () => ({ CatalogProductInterestSelect: () => <button>Products</button> }));
vi.mock('@/shared/components/entity-combobox', () => ({ EntityCombobox: () => <button>Agents</button> }));
import { AudiencePanel } from '../audience-panel';
const preview = { matched: 1, eligible: 1, missingEmail: 0, invalidEmail: 0, duplicateEmail: 0, staffEmail: 0, unsubscribed: 0, blocked: 0, inactive: 0, recipientNotAllowed: 0, recipients: [{ id: 'person', name: 'Saved recipient', recordType: 'Lead', email: 'one@example.test', company: '', phone: null }], meta: { page: 1, limit: 25, total: 1, hasMore: false } };
beforeEach(() => { vi.clearAllMocks(); api.fields.mockImplementation(async source => ({ data: campaignFields(source) })); api.preview.mockResolvedValue({ data: preview }); });
afterEach(cleanup);
it('offers one source, flat typed rules, and AND/OR rather than a mixed audience', async () => {
  render(<AudiencePanel onClose={vi.fn()} onCreated={vi.fn()} />);
  expect(screen.queryByRole('option', { name: /All Leads.*Contacts/ })).toBeNull();
  fireEvent.change(screen.getByLabelText('Match conditions'), { target: { value: 'OR' } });
  await waitFor(() => expect(api.preview).toHaveBeenCalledWith(expect.objectContaining({ source: 'LEADS', matchMode: 'OR', conditions: [] })));
  fireEvent.click(screen.getByText('+ Add Condition'));
  fireEvent.click(screen.getByText('Create Audience'));
  expect(api.create).not.toHaveBeenCalled();
  expect(screen.queryByText(/Invalid enum|Expected.*Hot/)).toBeNull();
  fireEvent.change(screen.getByLabelText('Condition 1 value'), { target: { value: 'Warm' } });
  await waitFor(() => expect(api.preview).toHaveBeenLastCalledWith(expect.objectContaining({ conditions: [{ field: 'status', operator: 'equals', value: 'Warm' }] })));
});
it('keeps incompatible source fields visible for correction instead of dropping criteria', async () => {
  render(<AudiencePanel onClose={vi.fn()} onCreated={vi.fn()} />);
  fireEvent.click(screen.getByText('+ Add Condition'));
  fireEvent.change(screen.getByLabelText('Condition 1 field'), { target: { value: 'companyName' } });
  fireEvent.change(screen.getByLabelText('Condition 1 value'), { target: { value: 'Acme' } });
  fireEvent.change(screen.getByLabelText('Source'), { target: { value: 'CONTACTS' } });
  fireEvent.click(screen.getByText('Create Audience'));
  expect(screen.getByRole('option', { name: /Unavailable field/ })).toBeTruthy();
  expect(screen.getByText(/unavailable for the selected source/)).toBeTruthy();
  expect(api.create).not.toHaveBeenCalled();
});
it('uses numeric serialization and reads a hidden active custom field', async () => {
  const definition = { id: '3b79321b-94fa-4d03-8557-e39a85a4be2c', name: 'Capacity', module: 'leads', group: 'Contact Details', type: 'Number', required: false, active: true, visibleInForm: false, visibleInDetails: true, order: 0, options: [], version: 1 } as const;
  api.fields.mockResolvedValue({ data: campaignFields('LEADS', [definition as never]) });
  render(<AudiencePanel onClose={vi.fn()} onCreated={vi.fn()} />);
  fireEvent.click(screen.getByText('+ Add Condition'));
  await screen.findByRole('option', { name: 'Capacity' });
  fireEvent.change(screen.getByLabelText('Condition 1 field'), { target: { value: `customFieldValues.${definition.id}` } });
  expect((screen.getByLabelText('Condition 1 value') as HTMLInputElement).type).toBe('number');
  await waitFor(() => expect(api.preview).toHaveBeenLastCalledWith(expect.objectContaining({ conditions: [{ field: `customFieldValues.${definition.id}`, operator: 'equals', value: 0 }] })));
});
it('keeps populated recipient rows visible during background preview refresh', async () => {
  render(<AudiencePanel onClose={vi.fn()} onCreated={vi.fn()} />);
  await screen.findByText('Saved recipient');
  let finish!: (value: unknown) => void;
  api.preview.mockImplementationOnce(() => new Promise(resolve => { finish = resolve; }));
  fireEvent.change(screen.getByLabelText('Match conditions'), { target: { value: 'OR' } });
  await waitFor(() => expect(api.preview).toHaveBeenCalledTimes(2));
  expect(screen.getByText('Saved recipient')).toBeTruthy();
  expect(screen.queryByRole('status', { name: 'Loading data' })).toBeNull();
  await act(async () => finish({ data: preview }));
});
