import { Router } from 'express';
import { ClientAdminRegisterSchema } from '../../core/auth/auth.dto';
import { authRateLimiter, passwordResetRateLimiter } from '../middleware/rate-limit.middleware';
import { authMiddleware } from '../middleware/auth.middleware';
import { validate } from '../middleware/validate.middleware';
import { LoginSchema, ForgotPasswordSchema, ResetPasswordSchema } from '../../core/auth/auth.dto';
import * as authController from '../../core/auth/auth.controller';
import { ChangePasswordSchema } from '../../core/auth/change-password.service';
import { changePasswordController } from '../../core/auth/change-password.controller';

const router = Router();
router.post('/invitations/accept', authRateLimiter, validate(ClientAdminRegisterSchema), authController.registerClientAdmin);
router.post('/login', authRateLimiter, validate(LoginSchema), authController.login);
router.post('/logout', authController.logout);
router.get('/me', authMiddleware, authController.me);
router.post('/forgot-password', passwordResetRateLimiter, validate(ForgotPasswordSchema), authController.forgotPassword);
router.post('/reset-password', passwordResetRateLimiter, validate(ResetPasswordSchema), authController.resetPassword);
router.post('/change-password', authRateLimiter, authMiddleware, validate(ChangePasswordSchema), changePasswordController);
router.get('/onboarding/status', authMiddleware, authController.getOnboardingStatus);
router.post('/onboarding/complete', authMiddleware, authController.completeOnboarding);
export default router;
