// ─── Contact & Organization ────────────────────────────────────────────────

export interface Organization {
  id: string;
  tenantId: string;
  name: string;
  industry?: string;
  productInterests?: string[];
  size?: string;
  website?: string;
  taxId?: string;
  assignedUserId?: string;
  tags?: string[];
  notes?: string;
  internalNotes?: string;
  customerType?: 'Prospect' | 'Active Customer' | 'Inactive Customer' | 'Former Customer';
  customerSince?: string;
  activeProducts?: string[];
  createdAt: string;
  isArchived?: boolean;
  // Location fields
  address?: string;
  city?: string;
  province?: string;
  country?: string;
  postalCode?: string;
}

export interface Contact {
  id: string;
  tenantId: string;
  organizationId?: string;
  companyName: string;
  contactPerson: string;
  jobTitle: string;
  email: string;
  phone: string;
  leadSource: string;
  estimatedValue: number;
  assignedUserId: string;
  expectedCloseDate: string;
  notes: string;
  status: 'Hot' | 'Warm' | 'Cold' | 'Cancelled' | 'Closed';
  lifecycleStage?: 'LEAD' | 'QUALIFIED' | 'CONTACT' | 'CUSTOMER' | 'CHURNED' | 'DISQUALIFIED';
  recordType?: 'Individual' | 'Organization';
  score: number;
  createdAt: string;
  isArchived?: boolean;
  archivedAt?: string;
  archivedBy?: string;
  archiveReason?: string;
  type?: 'Individual' | 'Organization';
  customerType?: 'Prospect' | 'Active Customer' | 'Inactive Customer' | 'Former Customer';
  customerSince?: string;
  activeProducts?: string[];
  qualifiedAt?: string;
  disqualifiedReason?: string;
  callStatus?: string;
  updateStatus?: string;
  contactNumbers?: { id: string; type: 'Telephone' | 'Mobile'; countryCode?: string; number: string; notes?: string }[];
  productInterests?: string[];
  address?: string;
  doNotContact?: boolean;
  // Enriched fields
  firstName?: string;
  middleName?: string;
  lastName?: string;
  suffix?: string;
  displayName?: string;
  preferredName?: string;
  department?: string;
  profilePhoto?: string;
  gender?: string;
  dateOfBirth?: string;
  secondaryEmail?: string;
  workEmail?: string;
  mobileNumber?: string;
  phoneCountryCode?: string;
  altPhone?: string;
  website?: string;
  linkedin?: string;
  facebook?: string;
  otherSocial?: string;
  businessType?: string;
  companySize?: string;
  orgOwner?: string;
  orgWebsite?: string;
  orgAddress?: string;
  taxId?: string;
  country?: string;
  region?: string;
  province?: string;
  city?: string;
  barangay?: string;
  postalCode?: string;
  streetAddress?: string;
  building?: string;
  floor?: string;
  unit?: string;
  assignedTeam?: string;
  ownerId?: string;
  createdBy?: string;
  lastUpdated?: string;
  tags?: string;
  customFields?: Record<string, string>;
  internalNotes?: string;
  priority?: 'Low' | 'Medium' | 'High' | 'Critical';
}
