/**
 * Bidirectional route map — App Router pathname ↔ legacy path string.
 * Single source of truth used by CrmLayout, auth pages, and route guards.
 */

export const PATHNAME_TO_PATH: Record<string, string> = {
  '/onboarding':                   'onboarding',
  '/dashboard':                    'dashboard',
  '/crm/leads':                    'leads',
  '/crm/customers':                'customers',
  '/crm/accounts':                 'accounts',
  '/crm/deals':                    'deals',
  '/crm/pipeline':                 'pipeline',
  '/automation/workflows':         'workflows',
  '/marketing/campaigns':          'campaigns',
  '/reporting':                    'reports',
  '/administration/users':         'users',
  '/settings':                     'settings',
  '/settings/account':             'account-details',
  '/settings/profile':             'profile-settings',
  '/operations/service-orders':    'service-orders',
  '/operations/tasks':             'technician-jobs',
  '/operations/assets':            'assets',
  '/operations/inventory':         'inventory',
  '/billing':                      'billing',
  '/billing/client':               'client-billing',
  '/administration/audit':         'audit-log',
  '/operations/taskboard':         'tasks',
  '/inbox':                        'inbox',
  '/notifications':                'notifications',
  '/admin/dashboard':              'admin-dashboard',
  '/admin/clients':                'admin-clients',
  '/admin/pricing':                'admin-pricing',
  '/admin/billing':                'admin-billing',
  '/admin/environments':           'admin-environments',
  '/admin/audit':                  'admin-audit-log',
  '/admin/payments':               'admin-payments',
  '/admin/revenue':                'admin-revenue',
  '/admin/refunds':                'admin-refunds',
};

// Reverse map — canonical pathname for each path (first match wins)
export const PATH_TO_PATHNAME: Record<string, string> = {
  'onboarding':          '/onboarding',
  'dashboard':           '/dashboard',
  'contacts':            '/crm/leads',
  'leads':               '/crm/leads',
  'customers':           '/crm/customers',
  'accounts':            '/crm/accounts',
  'deals':               '/crm/deals',
  'pipeline':            '/crm/pipeline',
  'workflows':           '/automation/workflows',
  'campaigns':           '/marketing/campaigns',
  'reports':             '/reporting',
  'users':               '/administration/users',
  'settings':            '/settings',
  'account-details':     '/settings/account',
  'profile-settings':    '/settings/profile',
  'service-orders':      '/operations/service-orders',
  'technician-jobs':     '/operations/tasks',
  'assets':              '/operations/assets',
  'inventory':           '/operations/inventory',
  'billing':             '/billing',
  'client-billing':      '/billing/client',
  'audit-log':           '/administration/audit',
  'tasks':               '/operations/taskboard',
  'inbox':               '/inbox',
  'notifications':       '/notifications',
  'admin-dashboard':     '/admin/dashboard',
  'admin-clients':       '/admin/clients',
  'admin-pricing':       '/admin/pricing',
  'admin-billing':       '/admin/billing',
  'admin-environments':  '/admin/environments',
  'admin-audit-log':     '/admin/audit',
  'admin-payments':      '/admin/payments',
  'admin-revenue':       '/admin/revenue',
  'admin-refunds':       '/admin/refunds',
};